import { v } from "convex/values";
import { mutation, query } from "./_generated/server";

// ═══════════════════════════════════════════════════════════════════
// SEED ALL 300 ENTERPRISE CLIENTS
// Populates enterprise_companies + enterprise_feature_configs
// ═══════════════════════════════════════════════════════════════════

const ALL_300_COMPANIES = [
  { id: "S1", name: "Local Service Business", size: "small", employees: "5-20", price: 199, subdomain: "localservice", agents: 3, description: "Plumbing, Electrical, Cleaning", icon: "🔧" },
  { id: "S2", name: "E-commerce Store", size: "small", employees: "5-30", price: 299, subdomain: "ecommercestore", agents: 5, description: "Online Retail / E-commerce", icon: "🛒" },
  { id: "S3", name: "Marketing Agency", size: "small", employees: "5-40", price: 349, subdomain: "marketingagency", agents: 5, description: "Digital Marketing & Advertising", icon: "📣" },
  { id: "S4", name: "Real Estate Agency", size: "small", employees: "5-35", price: 299, subdomain: "realestate", agents: 4, description: "Property Sales & Leasing", icon: "🏠" },
  { id: "S5", name: "SaaS Startup", size: "small", employees: "5-50", price: 399, subdomain: "saasstartup", agents: 5, description: "Software as a Service", icon: "💻" },
  { id: "M1", name: "Manufacturing Corp", size: "enterprise", employees: "500-5,000", price: 2999, subdomain: "manufacturing", agents: 10, description: "Industrial Manufacturing", icon: "🏭" },
  { id: "M2", name: "Healthcare Provider", size: "enterprise", employees: "500-10,000", price: 4999, subdomain: "healthcare", agents: 10, description: "Hospitals & Clinics", icon: "🏥" },
  { id: "M3", name: "Financial Services", size: "enterprise", employees: "500-10,000", price: 9999, subdomain: "financial", agents: 12, description: "Banking & Insurance", icon: "🏦" },
  { id: "M4", name: "Logistics & Supply Chain", size: "enterprise", employees: "500-10,000", price: 7499, subdomain: "logistics", agents: 10, description: "Transport & Warehousing", icon: "🚚" },
  { id: "M5", name: "Enterprise Tech", size: "enterprise", employees: "1,000-10,000", price: 14999, subdomain: "enterprisetech", agents: 15, description: "Enterprise Software & IT", icon: "🖥️" },
  { id: "H1", name: "Global Banking & Finance", size: "hyper-scale", employees: "500,000+", price: 49999, subdomain: "globalbanking", agents: 25, description: "50+ Countries · Fraud, KYC, Risk", icon: "🏦" },
  { id: "H2", name: "International Manufacturing", size: "hyper-scale", employees: "1,000,000+", price: 59999, subdomain: "globalmanufacturing", agents: 30, description: "40+ Countries · Supply Chain", icon: "🏭" },
  { id: "H3", name: "Worldwide E-commerce", size: "hyper-scale", employees: "800,000+", price: 69999, subdomain: "globalecommerce", agents: 35, description: "60+ Countries · Personalization", icon: "🛒" },
  { id: "H4", name: "Global Healthcare Network", size: "hyper-scale", employees: "600,000+", price: 79999, subdomain: "globalhealthcare", agents: 28, description: "30+ Countries · Patient, Telemedicine", icon: "🏥" },
  { id: "H5", name: "Multi-National Telecom", size: "hyper-scale", employees: "700,000+", price: 89999, subdomain: "globaltelecom", agents: 32, description: "45+ Countries · Network, Billing", icon: "📡" },
  { id: "H6", name: "Global Logistics & Shipping", size: "hyper-scale", employees: "500,000+", price: 99999, subdomain: "globallogistics", agents: 40, description: "80+ Countries · Route, Fleet", icon: "🚚" },
  { id: "H7", name: "International Energy Corp", size: "hyper-scale", employees: "400,000+", price: 119999, subdomain: "globalenergy", agents: 38, description: "35+ Countries · Grid, Analytics", icon: "⚡" },
  { id: "H8", name: "Worldwide Retail Chain", size: "hyper-scale", employees: "900,000+", price: 129999, subdomain: "globalretail", agents: 45, description: "55+ Countries · Inventory, Insights", icon: "🛍️" },
  { id: "H9", name: "Global Tech Conglomerate", size: "hyper-scale", employees: "1,500,000+", price: 149999, subdomain: "globaltech", agents: 50, description: "70+ Countries · DevOps, Security", icon: "🖥️" },
  { id: "H10", name: "Mega Government Agency", size: "hyper-scale", employees: "2,000,000+", price: 199999, subdomain: "government", agents: 60, description: "100+ Countries · Citizen, Compliance", icon: "🏛️" },
  { id: "HC11", name: "Dental Clinic Network", size: "small", employees: "50-200", price: 499, subdomain: "dentalnetwork", agents: 5, description: "Multi-location dental practices", icon: "🦷" },
  { id: "HC12", name: "Veterinary Hospital", size: "small", employees: "20-100", price: 399, subdomain: "vethospital", agents: 4, description: "Animal healthcare & pet services", icon: "🐾" },
  { id: "HC13", name: "Pharmacy Chain", size: "enterprise", employees: "200-2,000", price: 2499, subdomain: "pharmacychain", agents: 8, description: "Retail pharmacy & drug distribution", icon: "💊" },
  { id: "HC14", name: "Diagnostic Lab Network", size: "enterprise", employees: "300-3,000", price: 3499, subdomain: "diaglab", agents: 10, description: "Medical testing & pathology labs", icon: "🔬" },
  { id: "HC15", name: "Mental Health Practice", size: "small", employees: "10-50", price: 349, subdomain: "mentalhealth", agents: 4, description: "Psychiatry, therapy & counseling", icon: "🧠" },
  { id: "HC16", name: "Home Healthcare Agency", size: "small", employees: "30-150", price: 449, subdomain: "homehealth", agents: 5, description: "In-home patient care services", icon: "🏡" },
  { id: "HC17", name: "Fertility Clinic", size: "small", employees: "20-80", price: 599, subdomain: "fertility", agents: 4, description: "IVF & reproductive health", icon: "👶" },
  { id: "HC18", name: "Medical Devices Corp", size: "enterprise", employees: "500-5,000", price: 7999, subdomain: "meddevices", agents: 12, description: "Surgical & diagnostic equipment", icon: "🩺" },
  { id: "HC19", name: "Telehealth Platform", size: "enterprise", employees: "100-1,000", price: 4999, subdomain: "telehealth", agents: 10, description: "Virtual care & remote monitoring", icon: "📱" },
  { id: "HC20", name: "Health Insurance Provider", size: "enterprise", employees: "1,000-10,000", price: 12999, subdomain: "healthinsurance", agents: 15, description: "HMO, PPO & managed care", icon: "🛡️" },
  { id: "ED11", name: "Online Course Platform", size: "enterprise", employees: "30-150", price: 599, subdomain: "onlinecourse", agents: 6, description: "E-learning & course marketplace", icon: "📚" },
  { id: "ED12", name: "Tutoring Center", size: "small", employees: "10-50", price: 299, subdomain: "tutoring", agents: 3, description: "K-12 & test prep tutoring", icon: "📖" },
  { id: "ED13", name: "University Admin System", size: "enterprise", employees: "2,000-20,000", price: 9999, subdomain: "university", agents: 15, description: "Higher education management", icon: "🎓" },
  { id: "ED14", name: "Coding Bootcamp", size: "small", employees: "20-80", price: 499, subdomain: "bootcamp", agents: 5, description: "Tech skills training & placement", icon: "⌨️" },
  { id: "ED15", name: "Language School", size: "small", employees: "15-60", price: 349, subdomain: "languageschool", agents: 4, description: "Foreign language instruction", icon: "🌍" },
  { id: "ED16", name: "K-12 School Network", size: "enterprise", employees: "500-5,000", price: 6999, subdomain: "k12network", agents: 12, description: "Multi-campus school management", icon: "🏫" },
  { id: "ED17", name: "Corporate Training Platform", size: "enterprise", employees: "100-1,000", price: 3999, subdomain: "corptraining", agents: 8, description: "Enterprise L&D & upskilling", icon: "📋" },
  { id: "ED18", name: "Student Housing Platform", size: "small", employees: "20-80", price: 399, subdomain: "studenthousing", agents: 4, description: "Off-campus accommodation", icon: "🏠" },
  { id: "ED19", name: "Research Institution", size: "enterprise", employees: "200-2,000", price: 8999, subdomain: "research", agents: 14, description: "Academic & scientific research", icon: "🔬" },
  { id: "ED20", name: "EdTech Startup", size: "small", employees: "10-50", price: 449, subdomain: "edtech", agents: 5, description: "Educational technology products", icon: "💡" },
  { id: "TECH11", name: "Cybersecurity Firm", size: "enterprise", employees: "100-500", price: 1499, subdomain: "cybersec", agents: 10, description: "Threat detection & security ops", icon: "🔒" },
  { id: "TECH12", name: "Cloud Services Provider", size: "enterprise", employees: "50-200", price: 999, subdomain: "cloudservices", agents: 8, description: "IaaS, PaaS & managed cloud", icon: "☁️" },
  { id: "TECH13", name: "AI/ML Startup", size: "small", employees: "10-50", price: 599, subdomain: "aiml", agents: 6, description: "Artificial intelligence products", icon: "🤖" },
  { id: "TECH14", name: "DevOps Agency", size: "small", employees: "15-60", price: 499, subdomain: "devops", agents: 5, description: "CI/CD, infrastructure & SRE", icon: "⚙️" },
  { id: "TECH15", name: "Mobile App Studio", size: "small", employees: "10-40", price: 449, subdomain: "mobileapp", agents: 5, description: "iOS & Android development", icon: "📱" },
  { id: "TECH16", name: "Data Analytics Firm", size: "enterprise", employees: "100-500", price: 1299, subdomain: "dataanalytics", agents: 9, description: "Business intelligence & data", icon: "📊" },
  { id: "TECH17", name: "IoT Solutions Provider", size: "enterprise", employees: "80-300", price: 1199, subdomain: "iot", agents: 8, description: "Connected devices & edge computing", icon: "🌐" },
  { id: "TECH18", name: "Blockchain Company", size: "small", employees: "10-40", price: 699, subdomain: "blockchain", agents: 5, description: "DeFi, NFTs & Web3 infrastructure", icon: "⛓️" },
  { id: "TECH19", name: "SaaS Platform", size: "enterprise", employees: "100-1,000", price: 1999, subdomain: "saasplatform", agents: 10, description: "B2B SaaS products", icon: "🚀" },
  { id: "TECH20", name: "IT Consulting Firm", size: "enterprise", employees: "200-2,000", price: 3999, subdomain: "itconsulting", agents: 12, description: "Digital transformation & IT strategy", icon: "💼" },
  { id: "FIN11", name: "Microfinance Bank", size: "enterprise", employees: "200-2,000", price: 4999, subdomain: "microfinance", agents: 10, description: "SME lending & micro-credit", icon: "💰" },
  { id: "FIN12", name: "Insurance Brokerage", size: "small", employees: "20-80", price: 599, subdomain: "insurancebroker", agents: 5, description: "Multi-carrier insurance sales", icon: "🛡️" },
  { id: "FIN13", name: "Wealth Management Firm", size: "enterprise", employees: "100-1,000", price: 7999, subdomain: "wealthmgmt", agents: 12, description: "Portfolio & investment advisory", icon: "📈" },
  { id: "FIN14", name: "Payment Gateway Company", size: "enterprise", employees: "100-500", price: 5999, subdomain: "paygateway", agents: 10, description: "Digital payment processing", icon: "💳" },
  { id: "FIN15", name: "Credit Union", size: "enterprise", employees: "300-3,000", price: 6999, subdomain: "creditunion", agents: 11, description: "Member-owned financial co-op", icon: "🏛️" },
  { id: "FIN16", name: "Accounting Firm", size: "small", employees: "15-60", price: 449, subdomain: "accounting", agents: 5, description: "Audit, tax & advisory services", icon: "🧮" },
  { id: "FIN17", name: "Venture Capital Fund", size: "small", employees: "10-30", price: 799, subdomain: "vcfund", agents: 4, description: "Startup investment & portfolio", icon: "🎯" },
  { id: "FIN18", name: "Remittance Service", size: "enterprise", employees: "200-1,000", price: 3999, subdomain: "remittance", agents: 8, description: "Cross-border money transfers", icon: "💸" },
  { id: "FIN19", name: "Stock Brokerage", size: "enterprise", employees: "500-5,000", price: 9999, subdomain: "stockbroker", agents: 14, description: "Securities trading & research", icon: "📊" },
  { id: "FIN20", name: "Fintech Startup", size: "small", employees: "10-50", price: 599, subdomain: "fintech", agents: 6, description: "Innovative financial products", icon: "🚀" },
  { id: "RE11", name: "Property Management Co", size: "enterprise", employees: "100-500", price: 1299, subdomain: "propmgmt", agents: 8, description: "Residential & commercial management", icon: "🏢" },
  { id: "RE12", name: "Construction Company", size: "enterprise", employees: "200-2,000", price: 3999, subdomain: "construction", agents: 10, description: "General contracting & building", icon: "🏗️" },
  { id: "RE13", name: "Architectural Firm", size: "small", employees: "15-60", price: 499, subdomain: "architecture", agents: 5, description: "Building design & planning", icon: "📐" },
  { id: "RE14", name: "Co-working Space", size: "small", employees: "10-40", price: 399, subdomain: "coworking", agents: 4, description: "Shared office & community", icon: "🖥️" },
  { id: "RE15", name: "Vacation Rental Platform", size: "enterprise", employees: "50-300", price: 1999, subdomain: "vacationrental", agents: 8, description: "Short-term rental management", icon: "🏖️" },
  { id: "RE16", name: "Land Development Corp", size: "enterprise", employees: "100-1,000", price: 5999, subdomain: "landdev", agents: 10, description: "Raw land & subdivision development", icon: "🌍" },
  { id: "RE17", name: "Interior Design Studio", size: "small", employees: "10-30", price: 349, subdomain: "interiordesign", agents: 4, description: "Commercial & residential interiors", icon: "🎨" },
  { id: "RE18", name: "Real Estate Investment Trust", size: "hyper-scale", employees: "500-5,000", price: 19999, subdomain: "reit", agents: 20, description: "Portfolio of income properties", icon: "🏘️" },
  { id: "RE19", name: "Facility Management Co", size: "enterprise", employees: "300-3,000", price: 4999, subdomain: "facilitymgmt", agents: 10, description: "Building maintenance & ops", icon: "🔧" },
  { id: "RE20", name: "Smart Home Tech Company", size: "small", employees: "20-80", price: 599, subdomain: "smarthome", agents: 5, description: "IoT home automation products", icon: "🏠" },
  { id: "MF11", name: "Automotive Parts Manufacturer", size: "enterprise", employees: "500-5,000", price: 5999, subdomain: "autoparts", agents: 12, description: "OEM & aftermarket components", icon: "🚗" },
  { id: "MF12", name: "Food Processing Plant", size: "enterprise", employees: "300-3,000", price: 4999, subdomain: "foodprocessing", agents: 10, description: "Food production & packaging", icon: "🍎" },
  { id: "MF13", name: "Textile Factory", size: "enterprise", employees: "200-2,000", price: 3499, subdomain: "textile", agents: 8, description: "Fabric & garment manufacturing", icon: "🧵" },
  { id: "MF14", name: "Electronics Assembly", size: "enterprise", employees: "500-5,000", price: 6999, subdomain: "electronics", agents: 12, description: "PCB & consumer electronics", icon: "📟" },
  { id: "MF15", name: "Pharmaceutical Manufacturer", size: "enterprise", employees: "1,000-10,000", price: 14999, subdomain: "pharma", agents: 15, description: "Drug production & R&D", icon: "💊" },
  { id: "MF16", name: "Steel & Metals Plant", size: "enterprise", employees: "500-5,000", price: 7999, subdomain: "steel", agents: 12, description: "Metal fabrication & processing", icon: "⚙️" },
  { id: "MF17", name: "Furniture Manufacturer", size: "small", employees: "50-200", price: 799, subdomain: "furniture", agents: 5, description: "Office & home furniture", icon: "🪑" },
  { id: "MF18", name: "Chemical Processing Plant", size: "enterprise", employees: "300-3,000", price: 8999, subdomain: "chemical", agents: 14, description: "Industrial chemicals & polymers", icon: "🧪" },
  { id: "MF19", name: "Packaging Solutions Co", size: "enterprise", employees: "200-2,000", price: 4499, subdomain: "packaging", agents: 10, description: "Industrial & consumer packaging", icon: "📦" },
  { id: "MF20", name: "3D Printing Company", size: "small", employees: "10-50", price: 599, subdomain: "3dprinting", agents: 5, description: "Rapid prototyping & additive mfg", icon: "🖨️" },
  { id: "LG11", name: "Last-Mile Delivery Service", size: "enterprise", employees: "200-2,000", price: 2999, subdomain: "lastmile", agents: 8, description: "Same-day & next-day delivery", icon: "🏍️" },
  { id: "LG12", name: "Freight Forwarding Company", size: "enterprise", employees: "100-1,000", price: 3999, subdomain: "freight", agents: 10, description: "International cargo shipping", icon: "🚢" },
  { id: "LG13", name: "Cold Chain Logistics", size: "enterprise", employees: "200-2,000", price: 4999, subdomain: "coldchain", agents: 10, description: "Temperature-controlled transport", icon: "❄️" },
  { id: "LG14", name: "Warehouse & Fulfillment", size: "enterprise", employees: "300-3,000", price: 5999, subdomain: "warehouse", agents: 12, description: "3PL & order fulfillment", icon: "🏭" },
  { id: "LG15", name: "Courier Service", size: "small", employees: "50-200", price: 599, subdomain: "courier", agents: 4, description: "Express document & parcel delivery", icon: "📮" },
  { id: "LG16", name: "Fleet Management Company", size: "enterprise", employees: "100-1,000", price: 3499, subdomain: "fleetmgmt", agents: 8, description: "Vehicle leasing & telematics", icon: "🚛" },
  { id: "LG17", name: "Drone Delivery Startup", size: "small", employees: "10-50", price: 799, subdomain: "dronedelivery", agents: 5, description: "UAV logistics & aerial delivery", icon: "🛸" },
  { id: "LG18", name: "Rail Freight Operator", size: "enterprise", employees: "500-5,000", price: 7999, subdomain: "railfreight", agents: 14, description: "Bulk & intermodal rail transport", icon: "🚂" },
  { id: "LG19", name: "E-commerce Fulfillment Hub", size: "enterprise", employees: "200-2,000", price: 4499, subdomain: "ecommfulfill", agents: 10, description: "Marketplace order processing", icon: "📦" },
  { id: "LG20", name: "Customs Brokerage Firm", size: "small", employees: "20-80", price: 499, subdomain: "customs", agents: 5, description: "Import/export clearance", icon: "🛃" },
  { id: "RT11", name: "Fashion Boutique Chain", size: "enterprise", employees: "200-2,000", price: 3499, subdomain: "fashion", agents: 8, description: "Apparel & accessories retail", icon: "👗" },
  { id: "RT12", name: "Grocery Store Chain", size: "enterprise", employees: "500-5,000", price: 5999, subdomain: "grocery", agents: 12, description: "Supermarket & fresh produce", icon: "🥑" },
  { id: "RT13", name: "Electronics Retailer", size: "enterprise", employees: "300-3,000", price: 4999, subdomain: "electronicsretail", agents: 10, description: "Consumer electronics & gadgets", icon: "📱" },
  { id: "RT14", name: "Home Improvement Store", size: "enterprise", employees: "200-2,000", price: 3999, subdomain: "homeimprove", agents: 10, description: "Hardware & building materials", icon: "🔨" },
  { id: "RT15", name: "Pet Supply Store", size: "small", employees: "10-50", price: 399, subdomain: "petsupply", agents: 4, description: "Pet food, toys & accessories", icon: "🐕" },
  { id: "RT16", name: "Luxury Goods Retailer", size: "enterprise", employees: "100-1,000", price: 6999, subdomain: "luxury", agents: 10, description: "High-end fashion & jewelry", icon: "💎" },
  { id: "RT17", name: "Sporting Goods Store", size: "small", employees: "20-80", price: 449, subdomain: "sportinggoods", agents: 5, description: "Athletic equipment & apparel", icon: "⚽" },
  { id: "RT18", name: "Convenience Store Chain", size: "enterprise", employees: "300-3,000", price: 3999, subdomain: "convenience", agents: 10, description: "Neighborhood quick-stop stores", icon: "🏪" },
  { id: "RT19", name: "Baby & Kids Store", size: "small", employees: "15-60", price: 399, subdomain: "babystore", agents: 4, description: "Children clothing & gear", icon: "👶" },
  { id: "RT20", name: "Automotive Parts Retailer", size: "enterprise", employees: "200-2,000", price: 3499, subdomain: "autoretail", agents: 8, description: "Car parts & accessories", icon: "🔧" },
  { id: "HO11", name: "Hotel Chain", size: "enterprise", employees: "500-5,000", price: 7999, subdomain: "hotelchain", agents: 14, description: "Multi-property hotel management", icon: "🏨" },
  { id: "HO12", name: "Restaurant Chain", size: "enterprise", employees: "300-3,000", price: 4999, subdomain: "restchain", agents: 10, description: "Franchise & multi-location dining", icon: "🍽️" },
  { id: "HO13", name: "Event Planning Company", size: "small", employees: "10-40", price: 449, subdomain: "eventplanning", agents: 5, description: "Corporate & social events", icon: "🎉" },
  { id: "HO14", name: "Catering Service", size: "small", employees: "20-80", price: 399, subdomain: "catering", agents: 4, description: "Corporate & wedding catering", icon: "🍱" },
  { id: "HO15", name: "Spa & Wellness Center", size: "small", employees: "15-60", price: 399, subdomain: "spa", agents: 4, description: "Beauty, massage & wellness", icon: "🧖" },
  { id: "HO16", name: "Nightclub & Lounge", size: "small", employees: "20-80", price: 499, subdomain: "nightclub", agents: 4, description: "Entertainment & nightlife venues", icon: "🎶" },
  { id: "HO17", name: "Travel Agency", size: "small", employees: "10-50", price: 399, subdomain: "travelagency", agents: 5, description: "Tour packages & bookings", icon: "✈️" },
  { id: "HO18", name: "Resort & Casino", size: "hyper-scale", employees: "1,000-10,000", price: 19999, subdomain: "resortcasino", agents: 18, description: "Luxury resort & gaming", icon: "🎰" },
  { id: "HO19", name: "Coffee Shop Chain", size: "enterprise", employees: "100-1,000", price: 1999, subdomain: "coffeeshop", agents: 6, description: "Specialty coffee & cafe chain", icon: "☕" },
  { id: "HO20", name: "Food Delivery Platform", size: "enterprise", employees: "200-2,000", price: 3999, subdomain: "fooddelivery", agents: 10, description: "Restaurant delivery aggregator", icon: "🛵" },
  { id: "LG21", name: "Law Firm (Full Service)", size: "enterprise", employees: "200-2,000", price: 5999, subdomain: "lawfirm", agents: 12, description: "Corporate, litigation & IP law", icon: "⚖️" },
  { id: "LG22", name: "Patent Attorney Office", size: "small", employees: "10-30", price: 699, subdomain: "patent", agents: 5, description: "IP filing & prosecution", icon: "📝" },
  { id: "LG23", name: "Immigration Law Firm", size: "small", employees: "10-40", price: 499, subdomain: "immigration", agents: 5, description: "Visa, green card & citizenship", icon: "🌍" },
  { id: "LG24", name: "Mediation Center", size: "small", employees: "10-30", price: 399, subdomain: "mediation", agents: 4, description: "Alternative dispute resolution", icon: "🤝" },
  { id: "LG25", name: "Legal Tech Company", size: "enterprise", employees: "100-500", price: 2999, subdomain: "legaltech", agents: 8, description: "Contract management & e-discovery", icon: "💻" },
  { id: "LG26", name: "Compliance Consultancy", size: "enterprise", employees: "100-1,000", price: 4999, subdomain: "compliance", agents: 10, description: "Regulatory compliance & audit", icon: "📋" },
  { id: "LG27", name: "Corporate Law Department", size: "enterprise", employees: "50-300", price: 3999, subdomain: "corplaw", agents: 8, description: "In-house legal team support", icon: "🏛️" },
  { id: "LG28", name: "Intellectual Property Firm", size: "small", employees: "10-40", price: 599, subdomain: "ipfirm", agents: 5, description: "Trademarks, copyrights & patents", icon: "©️" },
  { id: "LG29", name: "Family Law Practice", size: "small", employees: "5-20", price: 349, subdomain: "familylaw", agents: 3, description: "Divorce, custody & adoption", icon: "👨‍👩‍👧" },
  { id: "LG30", name: "Tax Advisory Firm", size: "enterprise", employees: "100-1,000", price: 3999, subdomain: "taxadvisory", agents: 8, description: "Tax planning & preparation", icon: "🧾" },
  { id: "AG11", name: "Commercial Farming Operation", size: "enterprise", employees: "200-2,000", price: 3999, subdomain: "farm", agents: 10, description: "Large-scale crop production", icon: "🌾" },
  { id: "AG12", name: "Livestock Ranch", size: "enterprise", employees: "100-1,000", price: 2999, subdomain: "ranch", agents: 8, description: "Cattle, poultry & dairy farming", icon: "🐄" },
  { id: "AG13", name: "Agri-Tech Startup", size: "small", employees: "10-50", price: 599, subdomain: "agritech", agents: 5, description: "Precision agriculture & drones", icon: "🤖" },
  { id: "AG14", name: "Food Distribution Company", size: "enterprise", employees: "200-2,000", price: 4999, subdomain: "fooddist", agents: 10, description: "Wholesale food & produce", icon: "🚛" },
  { id: "AG15", name: "Seed & Fertilizer Supplier", size: "enterprise", employees: "100-1,000", price: 3499, subdomain: "seedfert", agents: 8, description: "Agricultural inputs & supplies", icon: "🌱" },
  { id: "AG16", name: "Aquaculture Farm", size: "enterprise", employees: "100-1,000", price: 3999, subdomain: "aquaculture", agents: 8, description: "Fish & shrimp farming", icon: "🐟" },
  { id: "AG17", name: "Organic Farm Network", size: "small", employees: "20-80", price: 499, subdomain: "organicfarm", agents: 4, description: "Certified organic produce", icon: "🥬" },
  { id: "AG18", name: "Agricultural Cooperative", size: "enterprise", employees: "300-3,000", price: 2999, subdomain: "coop", agents: 8, description: "Farmer-owned cooperative", icon: "🤝" },
  { id: "AG19", name: "Greenhouse Operation", size: "small", employees: "20-80", price: 599, subdomain: "greenhouse", agents: 5, description: "Controlled environment agriculture", icon: "🏡" },
  { id: "AG20", name: "Forestry & Timber Company", size: "enterprise", employees: "200-2,000", price: 4499, subdomain: "timber", agents: 10, description: "Logging & wood products", icon: "🌲" },
  { id: "EP21", name: "Solar Energy Company", size: "enterprise", employees: "200-2,000", price: 4999, subdomain: "solar", agents: 10, description: "Solar panel installation & maintenance", icon: "☀️" },
  { id: "EP22", name: "Water Treatment Plant", size: "enterprise", employees: "300-3,000", price: 6999, subdomain: "watertreatment", agents: 12, description: "Municipal & industrial water treatment", icon: "💧" },
  { id: "EP23", name: "Wind Farm Operator", size: "enterprise", employees: "100-1,000", price: 5999, subdomain: "windfarm", agents: 10, description: "Wind turbine energy generation", icon: "🌬️" },
  { id: "EP24", name: "Electric Utility Company", size: "hyper-scale", employees: "5,000-50,000", price: 29999, subdomain: "electricutil", agents: 20, description: "Power generation & distribution", icon: "⚡" },
  { id: "EP25", name: "Natural Gas Provider", size: "enterprise", employees: "1,000-10,000", price: 19999, subdomain: "naturalgas", agents: 15, description: "Gas extraction & distribution", icon: "🔥" },
  { id: "EP26", name: "Waste Management Company", size: "enterprise", employees: "200-2,000", price: 3999, subdomain: "wastemanage", agents: 8, description: "Garbage collection & recycling", icon: "♻️" },
  { id: "EP27", name: "EV Charging Network", size: "small", employees: "20-100", price: 799, subdomain: "evcharging", agents: 6, description: "Electric vehicle charging stations", icon: "🔌" },
  { id: "EP28", name: "Nuclear Energy Corp", size: "hyper-scale", employees: "10,000-100,000", price: 49999, subdomain: "nuclear", agents: 25, description: "Nuclear power generation", icon: "☢️" },
  { id: "EP29", name: "Hydroelectric Plant", size: "enterprise", employees: "500-5,000", price: 8999, subdomain: "hydroelectric", agents: 12, description: "Dam-based power generation", icon: "🌊" },
  { id: "EP30", name: "Smart Grid Technology", size: "enterprise", employees: "100-500", price: 7999, subdomain: "smartgrid", agents: 10, description: "Intelligent power distribution", icon: "🏗️" },
  { id: "ME21", name: "Film Production Studio", size: "enterprise", employees: "100-1,000", price: 7999, subdomain: "filmstudio", agents: 12, description: "Movie & TV series production", icon: "🎬" },
  { id: "ME22", name: "Music Streaming Platform", size: "hyper-scale", employees: "1,000-10,000", price: 39999, subdomain: "musicstream", agents: 22, description: "Audio streaming & distribution", icon: "🎵" },
  { id: "ME23", name: "Game Development Studio", size: "small", employees: "20-100", price: 899, subdomain: "gamedev", agents: 6, description: "Video game creation & publishing", icon: "🎮" },
  { id: "ME24", name: "Broadcasting Network", size: "hyper-scale", employees: "5,000-50,000", price: 29999, subdomain: "broadcast", agents: 20, description: "TV & radio broadcasting", icon: "📺" },
  { id: "ME25", name: "Digital Media Agency", size: "small", employees: "15-60", price: 599, subdomain: "digitalmedia", agents: 5, description: "Content creation & social media", icon: "📱" },
  { id: "ME26", name: "Podcast Network", size: "small", employees: "10-40", price: 399, subdomain: "podcast", agents: 4, description: "Podcast production & hosting", icon: "🎙️" },
  { id: "ME27", name: "Animation Studio", size: "enterprise", employees: "200-2,000", price: 5999, subdomain: "animation", agents: 10, description: "2D & 3D animation production", icon: "🎨" },
  { id: "ME28", name: "Esports Organization", size: "small", employees: "20-80", price: 699, subdomain: "esports", agents: 5, description: "Competitive gaming & teams", icon: "🏆" },
  { id: "ME29", name: "Event Production Company", size: "small", employees: "30-150", price: 799, subdomain: "eventprod", agents: 5, description: "Concert & festival production", icon: "🎪" },
  { id: "ME30", name: "OTT Platform", size: "hyper-scale", employees: "2,000-20,000", price: 49999, subdomain: "ott", agents: 25, description: "Over-the-top streaming service", icon: "📱" },
  { id: "GOV21", name: "Municipal Government", size: "enterprise", employees: "500-5,000", price: 9999, subdomain: "municipal", agents: 15, description: "City & local government services", icon: "🏛️" },
  { id: "GOV22", name: "Tax Authority", size: "enterprise", employees: "1,000-10,000", price: 14999, subdomain: "taxauthority", agents: 18, description: "Revenue collection & compliance", icon: "💰" },
  { id: "GOV23", name: "Immigration Department", size: "enterprise", employees: "2,000-20,000", price: 19999, subdomain: "immigration", agents: 20, description: "Visa processing & border control", icon: "🛂" },
  { id: "GOV24", name: "Public Health Agency", size: "enterprise", employees: "1,000-10,000", price: 12999, subdomain: "publichealth", agents: 15, description: "Disease control & health policy", icon: "🏥" },
  { id: "GOV25", name: "Public Works Department", size: "enterprise", employees: "500-5,000", price: 8999, subdomain: "publicworks", agents: 12, description: "Infrastructure & road maintenance", icon: "🛣️" },
  { id: "GOV26", name: "Education Ministry", size: "hyper-scale", employees: "10,000-100,000", price: 39999, subdomain: "eduministry", agents: 22, description: "National education policy & oversight", icon: "🎓" },
  { id: "GOV27", name: "Law Enforcement Agency", size: "enterprise", employees: "5,000-50,000", price: 29999, subdomain: "lawenforce", agents: 20, description: "Police & public safety operations", icon: "🚔" },
  { id: "GOV28", name: "Social Welfare Agency", size: "enterprise", employees: "500-5,000", price: 7999, subdomain: "socialwelfare", agents: 12, description: "Social services & benefit programs", icon: "🤲" },
  { id: "GOV29", name: "Environmental Protection Agency", size: "enterprise", employees: "500-5,000", price: 9999, subdomain: "epa", agents: 14, description: "Environmental regulation & enforcement", icon: "🌍" },
  { id: "GOV30", name: "Central Bank", size: "hyper-scale", employees: "5,000-50,000", price: 99999, subdomain: "centralbank", agents: 30, description: "Monetary policy & financial regulation", icon: "🏦" },
  { id: "NP21", name: "International Aid Organization", size: "hyper-scale", employees: "5,000-50,000", price: 29999, subdomain: "aidorg", agents: 20, description: "Humanitarian relief & development", icon: "🕊️" },
  { id: "NP22", name: "Environmental NGO", size: "enterprise", employees: "200-2,000", price: 4999, subdomain: "envngo", agents: 10, description: "Conservation & climate action", icon: "🌿" },
  { id: "NP23", name: "Education Charity", size: "small", employees: "20-80", price: 399, subdomain: "educharity", agents: 4, description: "Schools & literacy programs", icon: "📚" },
  { id: "NP24", name: "Healthcare Foundation", size: "enterprise", employees: "300-3,000", price: 6999, subdomain: "healthfound", agents: 10, description: "Medical research & patient support", icon: "❤️" },
  { id: "NP25", name: "Disaster Relief Agency", size: "enterprise", employees: "500-5,000", price: 9999, subdomain: "disasterrelief", agents: 14, description: "Emergency response & recovery", icon: "🆘" },
  { id: "NP26", name: "Animal Welfare Organization", size: "small", employees: "20-100", price: 449, subdomain: "animalwelfare", agents: 4, description: "Animal rescue & protection", icon: "🐾" },
  { id: "NP27", name: "Human Rights Organization", size: "enterprise", employees: "200-2,000", price: 5999, subdomain: "humanrights", agents: 10, description: "Civil liberties & advocacy", icon: "✊" },
  { id: "NP28", name: "Community Development Corp", size: "small", employees: "15-60", price: 349, subdomain: "communitydev", agents: 4, description: "Neighborhood improvement programs", icon: "🏘️" },
  { id: "NP29", name: "Youth Empowerment Foundation", size: "small", employees: "10-40", price: 299, subdomain: "youthempower", agents: 3, description: "Skills training & mentorship", icon: "🌟" },
  { id: "NP30", name: "Religious Organization", size: "small", employees: "10-50", price: 299, subdomain: "religious", agents: 3, description: "Faith-based community services", icon: "⛪" },
  { id: "MN21", name: "Gold Mining Company", size: "enterprise", employees: "1,000-10,000", price: 19999, subdomain: "goldmine", agents: 16, description: "Gold extraction & refining", icon: "🥇" },
  { id: "MN22", name: "Oil & Gas Exploration", size: "hyper-scale", employees: "10,000-100,000", price: 59999, subdomain: "oilgas", agents: 30, description: "Petroleum exploration & drilling", icon: "🛢️" },
  { id: "MN23", name: "Diamond Mining Corp", size: "enterprise", employees: "2,000-20,000", price: 39999, subdomain: "diamond", agents: 20, description: "Diamond mining & sorting", icon: "💎" },
  { id: "MN24", name: "Copper Mining Company", size: "enterprise", employees: "1,000-10,000", price: 14999, subdomain: "copper", agents: 14, description: "Copper ore extraction & processing", icon: "🔶" },
  { id: "MN25", name: "Quarry Operations", size: "enterprise", employees: "200-2,000", price: 5999, subdomain: "quarry", agents: 10, description: "Stone, sand & gravel extraction", icon: "⛰️" },
  { id: "MN26", name: "Lithium Mining Corp", size: "enterprise", employees: "500-5,000", price: 19999, subdomain: "lithium", agents: 16, description: "Battery-grade lithium extraction", icon: "🔋" },
  { id: "MN27", name: "Mining Equipment Supplier", size: "enterprise", employees: "500-5,000", price: 8999, subdomain: "minequip", agents: 12, description: "Heavy machinery & tools for mining", icon: "⛏️" },
  { id: "MN28", name: "Mineral Processing Plant", size: "enterprise", employees: "300-3,000", price: 7999, subdomain: "mineralproc", agents: 10, description: "Ore crushing & concentration", icon: "🏗️" },
  { id: "MN29", name: "Rare Earth Mining", size: "enterprise", employees: "500-5,000", price: 24999, subdomain: "rareearth", agents: 18, description: "Rare earth element extraction", icon: "🧲" },
  { id: "MN30", name: "Mining Safety Consulting", size: "small", employees: "20-80", price: 699, subdomain: "minesafety", agents: 5, description: "Mine safety audits & training", icon: "⛑️" },
  { id: "AU21", name: "Car Dealership Chain", size: "enterprise", employees: "500-5,000", price: 7999, subdomain: "cardealership", agents: 12, description: "New & used vehicle sales", icon: "🚗" },
  { id: "AU22", name: "Auto Repair Shop Chain", size: "enterprise", employees: "200-2,000", price: 3999, subdomain: "autorepair", agents: 8, description: "Vehicle maintenance & repair", icon: "🔧" },
  { id: "AU23", name: "Electric Vehicle Manufacturer", size: "hyper-scale", employees: "50,000-500,000", price: 89999, subdomain: "evmanufacturer", agents: 35, description: "EV design & manufacturing", icon: "⚡" },
  { id: "AU24", name: "Car Rental Company", size: "enterprise", employees: "1,000-10,000", price: 9999, subdomain: "carrental", agents: 14, description: "Fleet rental & leasing", icon: "🚙" },
  { id: "AU25", name: "Ride-sharing Platform", size: "hyper-scale", employees: "10,000-100,000", price: 69999, subdomain: "rideshare", agents: 30, description: "On-demand transportation", icon: "🚕" },
  { id: "AU26", name: "Auto Insurance Company", size: "enterprise", employees: "1,000-10,000", price: 12999, subdomain: "autoinsurance", agents: 15, description: "Vehicle & driver insurance", icon: "🛡️" },
  { id: "AU27", name: "Tire Manufacturing Company", size: "enterprise", employees: "2,000-20,000", price: 14999, subdomain: "tires", agents: 14, description: "Tire production & distribution", icon: "⭕" },
  { id: "AU28", name: "Autonomous Vehicle Startup", size: "small", employees: "50-200", price: 1299, subdomain: "autonomous", agents: 8, description: "Self-driving technology R&D", icon: "🤖" },
  { id: "AU29", name: "Motorcycle Manufacturer", size: "enterprise", employees: "1,000-10,000", price: 9999, subdomain: "motorcycle", agents: 12, description: "Motorcycle & scooter production", icon: "🏍️" },
  { id: "AU30", name: "Auto Parts E-commerce", size: "small", employees: "20-80", price: 599, subdomain: "autopartsstore", agents: 5, description: "Online auto parts marketplace", icon: "🛒" },
  { id: "SR21", name: "Professional Sports Team", size: "enterprise", employees: "100-1,000", price: 9999, subdomain: "sportsteam", agents: 14, description: "League sports franchise", icon: "⚽" },
  { id: "SR22", name: "Fitness Gym Chain", size: "enterprise", employees: "500-5,000", price: 5999, subdomain: "gymchain", agents: 10, description: "Fitness centers & personal training", icon: "💪" },
  { id: "SR23", name: "Golf Course & Resort", size: "enterprise", employees: "200-2,000", price: 7999, subdomain: "golfresort", agents: 10, description: "Golf courses & club management", icon: "⛳" },
  { id: "SR24", name: "Ski Resort", size: "enterprise", employees: "300-3,000", price: 8999, subdomain: "skiresort", agents: 12, description: "Winter sports & mountain resort", icon: "⛷️" },
  { id: "SR25", name: "Sports Equipment Manufacturer", size: "enterprise", employees: "1,000-10,000", price: 9999, subdomain: "sportequip", agents: 12, description: "Athletic gear & equipment", icon: "🏈" },
  { id: "SR26", name: "Water Park", size: "small", employees: "100-500", price: 1299, subdomain: "waterpark", agents: 6, description: "Aquatic entertainment venue", icon: "🏊" },
  { id: "SR27", name: "Sports Betting Platform", size: "enterprise", employees: "200-2,000", price: 14999, subdomain: "sportsbet", agents: 15, description: "Online sports wagering", icon: "🎰" },
  { id: "SR28", name: "Yoga & Wellness Studio", size: "small", employees: "10-40", price: 349, subdomain: "yogastudio", agents: 3, description: "Yoga, meditation & wellness", icon: "🧘" },
  { id: "SR29", name: "Theme Park", size: "hyper-scale", employees: "5,000-50,000", price: 39999, subdomain: "themepark", agents: 25, description: "Amusement & entertainment park", icon: "🎢" },
  { id: "SR30", name: "Cycling Sports Company", size: "small", employees: "20-80", price: 499, subdomain: "cycling", agents: 4, description: "Bicycle retail & cycling events", icon: "🚴" },
  { id: "FB31", name: "Fashion Design House", size: "small", employees: "20-80", price: 799, subdomain: "fashiondesign", agents: 5, description: "High fashion & ready-to-wear", icon: "👗" },
  { id: "FB32", name: "Cosmetics Brand", size: "enterprise", employees: "500-5,000", price: 6999, subdomain: "cosmetics", agents: 10, description: "Makeup & skincare products", icon: "💄" },
  { id: "FB33", name: "Hair Salon Chain", size: "enterprise", employees: "200-2,000", price: 3999, subdomain: "hairsalon", agents: 8, description: "Hair styling & beauty services", icon: "💇" },
  { id: "FB34", name: "Jewelry Store Chain", size: "enterprise", employees: "300-3,000", price: 7999, subdomain: "jewelry", agents: 10, description: "Fine jewelry & watches", icon: "💍" },
  { id: "FB35", name: "Perfume & Fragrance Brand", size: "small", employees: "20-80", price: 699, subdomain: "perfume", agents: 5, description: "Designer fragrances", icon: "🌹" },
  { id: "FB36", name: "Footwear Brand", size: "enterprise", employees: "1,000-10,000", price: 9999, subdomain: "footwear", agents: 12, description: "Shoes & sneaker brand", icon: "👟" },
  { id: "FB37", name: "Nail Salon Chain", size: "small", employees: "50-200", price: 399, subdomain: "nailsalon", agents: 4, description: "Manicure, pedicure & nail art", icon: "💅" },
  { id: "FB38", name: "Sunglasses Brand", size: "small", employees: "15-60", price: 599, subdomain: "sunglasses", agents: 4, description: "Eyewear & sunglasses retail", icon: "🕶️" },
  { id: "FB39", name: "Textile & Fabric Company", size: "enterprise", employees: "500-5,000", price: 5999, subdomain: "textile", agents: 10, description: "Fabric wholesale & distribution", icon: "🧵" },
  { id: "FB40", name: "Sustainable Fashion Brand", size: "small", employees: "10-50", price: 599, subdomain: "sustainablefashion", agents: 5, description: "Eco-friendly & ethical clothing", icon: "🌿" },
  { id: "TC41", name: "Mobile Network Operator", size: "hyper-scale", employees: "10,000-100,000", price: 79999, subdomain: "mno", agents: 30, description: "Cellular network & SIM services", icon: "📡" },
  { id: "TC42", name: "Internet Service Provider", size: "enterprise", employees: "1,000-10,000", price: 19999, subdomain: "isp", agents: 18, description: "Broadband & fiber internet", icon: "🌐" },
  { id: "TC43", name: "VoIP Provider", size: "small", employees: "20-100", price: 599, subdomain: "voip", agents: 5, description: "Internet-based phone services", icon: "📞" },
  { id: "TC44", name: "Cable TV Provider", size: "enterprise", employees: "1,000-10,000", price: 14999, subdomain: "cabletv", agents: 14, description: "Cable & satellite television", icon: "📺" },
  { id: "TC45", name: "5G Infrastructure Company", size: "enterprise", employees: "500-5,000", price: 29999, subdomain: "fiveg", agents: 20, description: "5G tower & infrastructure", icon: "📶" },
  { id: "TC46", name: "Satellite Communications", size: "hyper-scale", employees: "5,000-50,000", price: 59999, subdomain: "satellite", agents: 28, description: "Satellite internet & broadcasting", icon: "🛰️" },
  { id: "TC47", name: "Fiber Optic Network Company", size: "enterprise", employees: "500-5,000", price: 19999, subdomain: "fiber", agents: 15, description: "Fiber optic cable installation", icon: "💡" },
  { id: "TC48", name: "Telecom Tower Company", size: "enterprise", employees: "1,000-10,000", price: 24999, subdomain: "towers", agents: 16, description: "Cell tower construction & leasing", icon: "🏗️" },
  { id: "TC49", name: "Submarine Cable Operator", size: "hyper-scale", employees: "2,000-20,000", price: 89999, subdomain: "subcable", agents: 30, description: "Undersea fiber cable networks", icon: "🌊" },
  { id: "TC50", name: "Unified Communications Platform", size: "enterprise", employees: "100-1,000", price: 4999, subdomain: "unifiedcomm", agents: 10, description: "Team messaging & video conferencing", icon: "💬" },
  { id: "INS51", name: "Life Insurance Company", size: "hyper-scale", employees: "10,000-100,000", price: 49999, subdomain: "lifeinsurance", agents: 25, description: "Term & whole life policies", icon: "🛡️" },
  { id: "INS52", name: "Property Insurance Provider", size: "enterprise", employees: "1,000-10,000", price: 14999, subdomain: "propertyins", agents: 14, description: "Home & commercial property", icon: "🏠" },
  { id: "INS53", name: "Reinsurance Company", size: "hyper-scale", employees: "2,000-20,000", price: 69999, subdomain: "reinsurance", agents: 28, description: "Insurance for insurance companies", icon: "🔄" },
  { id: "INS54", name: "Health Maintenance Org", size: "enterprise", employees: "2,000-20,000", price: 19999, subdomain: "hmo", agents: 16, description: "Managed health insurance plans", icon: "🏥" },
  { id: "INS55", name: "Pet Insurance Provider", size: "small", employees: "50-200", price: 599, subdomain: "petinsurance", agents: 5, description: "Pet health & accident coverage", icon: "🐕" },
  { id: "INS56", name: "Travel Insurance Company", size: "small", employees: "30-150", price: 499, subdomain: "travelins", agents: 4, description: "Trip cancellation & medical", icon: "✈️" },
  { id: "INS57", name: "Cyber Insurance Provider", size: "enterprise", employees: "100-500", price: 3999, subdomain: "cyberins", agents: 8, description: "Data breach & cyber liability", icon: "🔒" },
  { id: "INS58", name: "Marine Insurance Company", size: "enterprise", employees: "200-2,000", price: 5999, subdomain: "marineins", agents: 10, description: "Cargo & vessel insurance", icon: "🚢" },
  { id: "INS59", name: "Workers Compensation Fund", size: "enterprise", employees: "500-5,000", price: 7999, subdomain: "workerscomp", agents: 12, description: "Workplace injury coverage", icon: "⚙️" },
  { id: "INS60", name: "Crop Insurance Provider", size: "enterprise", employees: "200-2,000", price: 4999, subdomain: "cropins", agents: 8, description: "Agricultural crop protection", icon: "🌾" },
  { id: "ENV61", name: "Environmental Consultancy", size: "small", employees: "20-80", price: 699, subdomain: "envconsult", agents: 5, description: "EIA & environmental audits", icon: "🌿" },
  { id: "ENV62", name: "Carbon Credit Trading Platform", size: "enterprise", employees: "100-500", price: 4999, subdomain: "carboncredit", agents: 8, description: "Carbon offset marketplace", icon: "🌱" },
  { id: "ENV63", name: "Water Purification Company", size: "enterprise", employees: "200-2,000", price: 5999, subdomain: "waterpurify", agents: 10, description: "Clean water technology", icon: "💧" },
  { id: "ENV64", name: "Recycling Technology Startup", size: "small", employees: "10-50", price: 599, subdomain: "recycletech", agents: 5, description: "Advanced recycling solutions", icon: "♻️" },
  { id: "ENV65", name: "Air Quality Monitoring Company", size: "small", employees: "20-80", price: 499, subdomain: "airquality", agents: 4, description: "Pollution monitoring & analysis", icon: "🌬️" },
  { id: "ENV66", name: "Soil Remediation Company", size: "enterprise", employees: "100-1,000", price: 3999, subdomain: "soilremed", agents: 8, description: "Contaminated land cleanup", icon: "🌍" },
  { id: "ENV67", name: "Eco-Tourism Company", size: "small", employees: "20-80", price: 449, subdomain: "ecotourism", agents: 4, description: "Sustainable travel experiences", icon: "🏕️" },
  { id: "ENV68", name: "Environmental Monitoring Firm", size: "enterprise", employees: "100-500", price: 2999, subdomain: "envmonitor", agents: 7, description: "Environmental data collection", icon: "📡" },
  { id: "ENV69", name: "Green Building Consultancy", size: "small", employees: "10-40", price: 599, subdomain: "greenbuilding", agents: 5, description: "LEED & sustainable construction", icon: "🏢" },
  { id: "ENV70", name: "Hazardous Waste Disposal", size: "enterprise", employees: "200-2,000", price: 5999, subdomain: "hazwaste", agents: 10, description: "Industrial waste management", icon: "⚠️" },
  { id: "PS71", name: "Management Consulting Firm", size: "enterprise", employees: "500-5,000", price: 12999, subdomain: "mgmtconsult", agents: 14, description: "Strategy & operations consulting", icon: "💼" },
  { id: "PS72", name: "HR Consulting Firm", size: "enterprise", employees: "200-2,000", price: 5999, subdomain: "hrconsult", agents: 10, description: "Talent acquisition & development", icon: "👥" },
  { id: "PS73", name: "Executive Search Firm", size: "small", employees: "20-80", price: 899, subdomain: "execsearch", agents: 5, description: "C-suite & senior recruitment", icon: "🎯" },
  { id: "PS74", name: "Business Process Outsourcing", size: "enterprise", employees: "2,000-20,000", price: 9999, subdomain: "bpo", agents: 12, description: "Back-office & customer support", icon: "📞" },
  { id: "PS75", name: "PR & Communications Agency", size: "small", employees: "20-80", price: 599, subdomain: "pragency", agents: 5, description: "Public relations & media management", icon: "📰" },
  { id: "PS76", name: "Graphic Design Studio", size: "small", employees: "10-40", price: 399, subdomain: "graphicdesign", agents: 4, description: "Visual design & branding", icon: "🎨" },
  { id: "PS77", name: "Research & Advisory Firm", size: "enterprise", employees: "200-2,000", price: 8999, subdomain: "researchadvisory", agents: 12, description: "Market research & strategic advice", icon: "🔬" },
  { id: "PS78", name: "Translation & Localization Agency", size: "small", employees: "20-80", price: 499, subdomain: "translation", agents: 4, description: "Multilingual content services", icon: "🌍" },
  { id: "PS79", name: "Market Research Firm", size: "enterprise", employees: "100-1,000", price: 3999, subdomain: "marketresearch", agents: 8, description: "Consumer insights & analytics", icon: "📊" },
  { id: "PS80", name: "Coaching & Mentoring Firm", size: "small", employees: "10-40", price: 449, subdomain: "coaching", agents: 4, description: "Executive & career coaching", icon: "🤝" },
  { id: "TR81", name: "Passenger Airline", size: "hyper-scale", employees: "50,000-500,000", price: 89999, subdomain: "airline", agents: 35, description: "Commercial aviation services", icon: "✈️" },
  { id: "TR82", name: "Bus Transportation Company", size: "enterprise", employees: "500-5,000", price: 5999, subdomain: "bustransit", agents: 10, description: "Public & intercity bus services", icon: "🚌" },
  { id: "TR83", name: "Shipping Line", size: "hyper-scale", employees: "10,000-100,000", price: 69999, subdomain: "shippingline", agents: 28, description: "Container shipping & maritime", icon: "🚢" },
  { id: "TR84", name: "Moving & Relocation Company", size: "small", employees: "30-150", price: 499, subdomain: "movers", agents: 4, description: "Household & office relocation", icon: "📦" },
  { id: "TR85", name: "Charter Flight Company", size: "small", employees: "20-80", price: 899, subdomain: "charterflight", agents: 5, description: "Private jet & helicopter charter", icon: "🛩️" },
  { id: "TR86", name: "Parking Management Company", size: "enterprise", employees: "200-2,000", price: 3999, subdomain: "parking", agents: 8, description: "Parking lot & garage operations", icon: "🅿️" },
  { id: "TR87", name: "Towing Service Company", size: "small", employees: "20-80", price: 399, subdomain: "towing", agents: 4, description: "Vehicle towing & roadside assist", icon: "🚛" },
  { id: "TR88", name: "Logistics Technology Startup", size: "small", employees: "10-50", price: 699, subdomain: "logtech", agents: 5, description: "Supply chain SaaS platform", icon: "💻" },
  { id: "TR89", name: "Public Transit Authority", size: "hyper-scale", employees: "10,000-100,000", price: 49999, subdomain: "transit", agents: 25, description: "Urban mass transit system", icon: "🚇" },
  { id: "TR90", name: "Freight Brokerage Company", size: "enterprise", employees: "200-2,000", price: 4999, subdomain: "freightbroker", agents: 10, description: "Load matching & carrier management", icon: "📋" },
  { id: "FNB91", name: "Brewery & Distillery", size: "enterprise", employees: "500-5,000", price: 7999, subdomain: "brewery", agents: 10, description: "Beer, wine & spirits production", icon: "🍺" },
  { id: "FNB92", name: "Bakery Chain", size: "enterprise", employees: "200-2,000", price: 3999, subdomain: "bakerychain", agents: 8, description: "Bread & pastry production", icon: "🍞" },
  { id: "FNB93", name: "Ice Cream & Dessert Chain", size: "small", employees: "50-200", price: 599, subdomain: "icecream", agents: 4, description: "Frozen treats & desserts", icon: "🍦" },
  { id: "FNB94", name: "Juice Bar Chain", size: "small", employees: "30-150", price: 399, subdomain: "juicebar", agents: 4, description: "Fresh juice & smoothies", icon: "🥤" },
  { id: "FNB95", name: "Gourmet Food Producer", size: "small", employees: "20-80", price: 699, subdomain: "gourmet", agents: 5, description: "Artisan food products", icon: "🧀" },
  { id: "FNB96", name: "Wine Estate & Vineyard", size: "enterprise", employees: "100-1,000", price: 5999, subdomain: "winery", agents: 10, description: "Wine production & tasting", icon: "🍷" },
  { id: "FNB97", name: "Snack Food Manufacturer", size: "enterprise", employees: "500-5,000", price: 6999, subdomain: "snacks", agents: 10, description: "Chips, cookies & packaged snacks", icon: "🍿" },
  { id: "FNB98", name: "Coffee Roastery Chain", size: "small", employees: "30-150", price: 599, subdomain: "coffeeroastery", agents: 5, description: "Specialty coffee roasting", icon: "☕" },
  { id: "FNB99", name: "Dairy Processing Plant", size: "enterprise", employees: "200-2,000", price: 5999, subdomain: "dairy", agents: 10, description: "Milk, cheese & yogurt production", icon: "🥛" },
  { id: "FNB100", name: "Craft Soda Company", size: "small", employees: "10-50", price: 449, subdomain: "craftsoda", agents: 4, description: "Artisan soft drinks", icon: "🥤" },
  { id: "DEF101", name: "Private Security Firm", size: "enterprise", employees: "500-5,000", price: 7999, subdomain: "security", agents: 12, description: "Physical & digital security services", icon: "🛡️" },
  { id: "DEF102", name: "Defense Contractor", size: "hyper-scale", employees: "10,000-100,000", price: 99999, subdomain: "defensecontractor", agents: 30, description: "Military equipment & systems", icon: "🎖️" },
  { id: "DEF103", name: "Cybersecurity Operations Center", size: "enterprise", employees: "200-2,000", price: 9999, subdomain: "soc", agents: 14, description: "24/7 threat monitoring & response", icon: "🔍" },
  { id: "DEF104", name: "Surveillance Technology Company", size: "enterprise", employees: "100-1,000", price: 5999, subdomain: "surveillance", agents: 10, description: "CCTV & monitoring systems", icon: "📹" },
  { id: "DEF105", name: "Arms & Ammunition Manufacturer", size: "hyper-scale", employees: "5,000-50,000", price: 69999, subdomain: "armsmfg", agents: 25, description: "Military-grade weapons & ammo", icon: "🔫" },
  { id: "DEF106", name: "Border Control Technology", size: "enterprise", employees: "200-2,000", price: 8999, subdomain: "bordercontrol", agents: 12, description: "Border security & surveillance", icon: "🛂" },
  { id: "DEF107", name: "Risk Assessment Company", size: "small", employees: "20-80", price: 699, subdomain: "riskassess", agents: 5, description: "Threat analysis & risk evaluation", icon: "⚠️" },
  { id: "DEF108", name: "Armored Transport Company", size: "enterprise", employees: "300-3,000", price: 5999, subdomain: "armoredtransport", agents: 10, description: "Cash-in-transit & valuables", icon: "🏦" },
  { id: "DEF109", name: "Emergency Response Technology", size: "enterprise", employees: "100-500", price: 4999, subdomain: "emergencytech", agents: 8, description: "911 & dispatch systems", icon: "🚨" },
  { id: "DEF110", name: "Intelligence Analysis Firm", size: "enterprise", employees: "100-1,000", price: 7999, subdomain: "intelligence", agents: 12, description: "Open-source intelligence & analysis", icon: "🕵️" },
  { id: "AE111", name: "Aircraft Manufacturing", size: "hyper-scale", employees: "50,000-500,000", price: 129999, subdomain: "aircraftmfg", agents: 40, description: "Commercial & military aircraft", icon: "✈️" },
  { id: "AE112", name: "Space Exploration Company", size: "hyper-scale", employees: "10,000-100,000", price: 149999, subdomain: "space", agents: 45, description: "Rocket launches & satellite deployment", icon: "🚀" },
  { id: "AE113", name: "Aircraft Maintenance Company", size: "enterprise", employees: "500-5,000", price: 8999, subdomain: "aircraftmro", agents: 12, description: "Aircraft repair & overhaul", icon: "🔧" },
  { id: "AE114", name: "Airport Operations Company", size: "hyper-scale", employees: "5,000-50,000", price: 39999, subdomain: "airportops", agents: 22, description: "Airport management & services", icon: "🛫" },
  { id: "AE115", name: "Drone Manufacturing Company", size: "small", employees: "50-200", price: 899, subdomain: "dronemfg", agents: 6, description: "Commercial & consumer drones", icon: "🛸" },
  { id: "AE116", name: "Aviation Training Academy", size: "small", employees: "30-150", price: 699, subdomain: "aviationacademy", agents: 5, description: "Pilot & crew training", icon: "🎓" },
  { id: "AE117", name: "Air Cargo Company", size: "enterprise", employees: "1,000-10,000", price: 14999, subdomain: "aircargo", agents: 14, description: "Air freight & logistics", icon: "📦" },
  { id: "AE118", name: "Avionics Manufacturer", size: "enterprise", employees: "500-5,000", price: 12999, subdomain: "avionics", agents: 14, description: "Aircraft electronics & instruments", icon: "📡" },
  { id: "AE119", name: "Helicopter Services Company", size: "small", employees: "30-150", price: 799, subdomain: "heliservices", agents: 5, description: "Helicopter charter & air ambulance", icon: "🚁" },
  { id: "AE120", name: "Satellite Manufacturing Company", size: "hyper-scale", employees: "5,000-50,000", price: 79999, subdomain: "satmfg", agents: 30, description: "Satellite design & construction", icon: "🛰️" },
  { id: "MS121", name: "Container Shipping Line", size: "hyper-scale", employees: "20,000-200,000", price: 99999, subdomain: "containership", agents: 35, description: "Global container shipping", icon: "🚢" },
  { id: "MS122", name: "Port Authority", size: "hyper-scale", employees: "5,000-50,000", price: 59999, subdomain: "portauthority", agents: 25, description: "Port operations & management", icon: "⚓" },
  { id: "MS123", name: "Fishing Fleet Company", size: "enterprise", employees: "200-2,000", price: 4999, subdomain: "fishing", agents: 10, description: "Commercial fishing operations", icon: "🐟" },
  { id: "MS124", name: "Ship Building Company", size: "hyper-scale", employees: "5,000-50,000", price: 89999, subdomain: "shipbuilding", agents: 30, description: "Vessel construction & repair", icon: "🏗️" },
  { id: "MS125", name: "Marine Salvage Company", size: "enterprise", employees: "100-1,000", price: 5999, subdomain: "salvage", agents: 8, description: "Wreck removal & rescue", icon: "⚓" },
  { id: "MS126", name: "Offshore Oil Platform", size: "hyper-scale", employees: "5,000-50,000", price: 119999, subdomain: "offshore", agents: 35, description: "Deep-sea drilling & extraction", icon: "🛢️" },
  { id: "MS127", name: "Yacht & Boat Dealer", size: "small", employees: "20-80", price: 799, subdomain: "yachtdealer", agents: 5, description: "Luxury yacht & boat sales", icon: "🛥️" },
  { id: "MS128", name: "Maritime Law Firm", size: "small", employees: "15-60", price: 699, subdomain: "maritimelaw", agents: 5, description: "Admiralty & shipping law", icon: "⚖️" },
  { id: "MS129", name: "Cruise Line Company", size: "hyper-scale", employees: "20,000-200,000", price: 109999, subdomain: "cruiseline", agents: 38, description: "Luxury cruise operations", icon: "🛳️" },
  { id: "MS130", name: "Marine Insurance Provider", size: "enterprise", employees: "500-5,000", price: 8999, subdomain: "marineinsurance", agents: 12, description: "Hull, cargo & liability coverage", icon: "🛡️" },
];

const DEFAULT_FEATURES = [
  "orders", "customers", "reports", "invoices", "receipts",
  "qrcodes", "appointments", "marketing", "email_marketing",
  "business_hours", "ecommerce", "whatsapp", "telegram",
  "landing_pages", "surveys", "testimonials", "client_portal"
];

export const seedBatch = mutation({
  args: {
    companyIds: v.array(v.string()),
    adminToken: v.string(),
  },
  returns: v.any(),
  handler: async (ctx, args) => {
    const DEFAULT_FEATURES = [
      "orders", "customers", "reports", "invoices", "receipts",
      "qrcodes", "appointments", "marketing", "email_marketing",
      "business_hours", "ecommerce", "whatsapp", "telegram",
      "landing_pages", "surveys", "testimonials", "client_portal"
    ];

    let created = 0;
    let skipped = 0;

    for (const companyId of args.companyIds) {
      const existing = await ctx.db
        .query("enterprise_feature_configs")
        .filter((q) => q.eq(q.field("orgId"), companyId))
        .first();

      if (existing) { skipped++; continue; }

      await ctx.db.insert("enterprise_feature_configs", {
        orgId: companyId,
        features: DEFAULT_FEATURES,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      });
      created++;
    }

    return { created, skipped };
  },
});

export const getSeededCount = query({
  args: {},
  returns: v.any(),
  handler: async (ctx) => {
    const configs = await ctx.db.query("enterprise_feature_configs").take(500);
    return { configs: configs.length };
  },
});
