import { Phone } from "@convex-dev/auth/providers/Phone";

export const TermiiOTP = Phone({
  id: "termii-otp",
  async generateVerificationToken() {
    // Generate 6 digit OTP (Numeric)
    const bytes = crypto.getRandomValues(new Uint8Array(6));
    return Array.from(bytes, (b) => (b % 10).toString()).join("");
  },
  async sendVerificationRequest({ identifier: originalPhone, token }) {
    const apiKey = process.env.TERMII_API_KEY;
    const senderId = process.env.TERMII_SENDER_ID || "Dutchkem";
    
    // Normalize phone number
    let phone = originalPhone.replace(/\D/g, '');
    if (phone.startsWith('0')) {
      phone = '234' + phone.substring(1);
    }
    if (!phone.startsWith('234')) {
      phone = '234' + phone;
    }

    const IS_DEVELOPMENT = process.env.NODE_ENV !== 'production';

    if (!apiKey || (IS_DEVELOPMENT && phone.startsWith('234000'))) {
      console.warn("[OTP] TERMII_API_KEY not set or Demo number detected. Simulating OTP send.");
      console.log(`[OTP] ✅ Simulation for ${phone}: Your verification code is ${token}`);
      return;
    }

    console.log(`[OTP] Sending code to ${phone} via Termii...`);
    
    try {
      // We use the regular messaging API to send the token generated by Convex Auth
      // This ensures Convex Auth can verify it correctly.
      const response = await fetch("https://api.ng.termii.com/api/sms/send", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          to: phone,
          from: senderId,
          sms: `Your Dutchkem Ventures verification code is ${token}. Valid for 10 minutes.`,
          type: "plain",
          channel: "generic", // Changed from 'dnd' to 'generic' for better delivery
          api_key: apiKey,
        }),
      });

      const data = await response.json();
      
      if (!response.ok) {
        throw new Error(`Termii API error: ${JSON.stringify(data)}`);
      }
      
      console.log(`[OTP] ✅ Termii response: ${JSON.stringify(data)}`);
    } catch (error) {
      console.error("[OTP] Failed to send OTP via Termii:", error);
      // In development, we still want to see the code if the API fails
      if (IS_DEVELOPMENT) {
        console.log(`[OTP Fallback] Code for ${phone}: ${token}`);
      }
      throw error;
    }
  },
});
