/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as AwsEmailOTP from "../AwsEmailOTP.js";
import type * as TermiiOTP from "../TermiiOTP.js";
import type * as abandonedCheckouts from "../abandonedCheckouts.js";
import type * as academic_agent from "../academic_agent.js";
import type * as academic_chat from "../academic_chat.js";
import type * as adEngine from "../adEngine.js";
import type * as adOrchestrator from "../adOrchestrator.js";
import type * as ad_abtest from "../ad_abtest.js";
import type * as ad_alerts from "../ad_alerts.js";
import type * as ad_analytics_agg from "../ad_analytics_agg.js";
import type * as ad_auto_generator from "../ad_auto_generator.js";
import type * as ad_batch from "../ad_batch.js";
import type * as ad_budget from "../ad_budget.js";
import type * as ad_campaign_ai from "../ad_campaign_ai.js";
import type * as ad_compliance from "../ad_compliance.js";
import type * as ad_compliance_enhanced from "../ad_compliance_enhanced.js";
import type * as ad_compliance_precheck from "../ad_compliance_precheck.js";
import type * as ad_conversions from "../ad_conversions.js";
import type * as ad_dashboard from "../ad_dashboard.js";
import type * as ad_designer from "../ad_designer.js";
import type * as ad_monetization from "../ad_monetization.js";
import type * as ad_scheduling from "../ad_scheduling.js";
import type * as ad_webhooks from "../ad_webhooks.js";
import type * as admin from "../admin.js";
import type * as admin_auth from "../admin_auth.js";
import type * as admin_enterprise from "../admin_enterprise.js";
import type * as admin_enterprise_hub from "../admin_enterprise_hub.js";
import type * as admin_helpers from "../admin_helpers.js";
import type * as admin_payouts from "../admin_payouts.js";
import type * as affiliate_system from "../affiliate_system.js";
import type * as agent_analytics from "../agent_analytics.js";
import type * as agent_backups from "../agent_backups.js";
import type * as agent_marketplace from "../agent_marketplace.js";
import type * as agent_payments from "../agent_payments.js";
import type * as agent_performance from "../agent_performance.js";
import type * as agent_runtime from "../agent_runtime.js";
import type * as agent_tools from "../agent_tools.js";
import type * as agent_video_production from "../agent_video_production.js";
import type * as agentic_payments from "../agentic_payments.js";
import type * as agents_chat_factory from "../agents/chat_factory.js";
import type * as agents_config from "../agents/config.js";
import type * as agents_registry from "../agents/registry.js";
import type * as ai_factory from "../ai_factory.js";
import type * as ai_image_generator from "../ai_image_generator.js";
import type * as ai_router from "../ai_router.js";
import type * as analytics_dashboard from "../analytics_dashboard.js";
import type * as api_costs from "../api_costs.js";
import type * as api_docs from "../api_docs.js";
import type * as appointment_booking from "../appointment_booking.js";
import type * as auth from "../auth.js";
import type * as auth_helpers from "../auth_helpers.js";
import type * as autoPosting from "../autoPosting.js";
import type * as auto_heal from "../auto_heal.js";
import type * as auto_healer from "../auto_healer.js";
import type * as aws_otp from "../aws_otp.js";
import type * as aws_sigv4 from "../aws_sigv4.js";
import type * as bi_annual_upgrade from "../bi_annual_upgrade.js";
import type * as business_agent from "../business_agent.js";
import type * as business_chat from "../business_chat.js";
import type * as business_hours from "../business_hours.js";
import type * as cac_deductions from "../cac_deductions.js";
import type * as career_agent from "../career_agent.js";
import type * as career_chat from "../career_chat.js";
import type * as certification_agent from "../certification_agent.js";
import type * as certification_chat from "../certification_chat.js";
import type * as charity from "../charity.js";
import type * as chatbot from "../chatbot.js";
import type * as chatbotLeads from "../chatbotLeads.js";
import type * as classification from "../classification.js";
import type * as clientAnalytics from "../clientAnalytics.js";
import type * as client_2fa from "../client_2fa.js";
import type * as client_actions from "../client_actions.js";
import type * as client_history from "../client_history.js";
import type * as client_kyc from "../client_kyc.js";
import type * as client_payouts from "../client_payouts.js";
import type * as client_support from "../client_support.js";
import type * as client_wallet from "../client_wallet.js";
import type * as cloud_memory from "../cloud_memory.js";
import type * as communication from "../communication.js";
import type * as companion_agent from "../companion_agent.js";
import type * as composioClient from "../composioClient.js";
import type * as composioEnhanced from "../composioEnhanced.js";
import type * as composioEnhancement from "../composioEnhancement.js";
import type * as composioHub from "../composioHub.js";
import type * as composioToolkitDetails from "../composioToolkitDetails.js";
import type * as composio_admin from "../composio_admin.js";
import type * as content_agent from "../content_agent.js";
import type * as content_chat from "../content_chat.js";
import type * as credits from "../credits.js";
import type * as crm_hygiene from "../crm_hygiene.js";
import type * as crons from "../crons.js";
import type * as crossSell from "../crossSell.js";
import type * as crypto_pure from "../crypto_pure.js";
import type * as customer_database from "../customer_database.js";
import type * as customer_support from "../customer_support.js";
import type * as customer_support_bot from "../customer_support_bot.js";
import type * as dashboard from "../dashboard.js";
import type * as ecommerce from "../ecommerce.js";
import type * as emotional_ai from "../emotional_ai.js";
import type * as encryption from "../encryption.js";
import type * as enterprise_org_admin from "../enterprise/org_admin.js";
import type * as enterprise_org_bulk from "../enterprise/org_bulk.js";
import type * as enterprise_org_crud from "../enterprise/org_crud.js";
import type * as enterprise_org_transactions from "../enterprise/org_transactions.js";
import type * as enterprise_audit_logs from "../enterprise_audit_logs.js";
import type * as enterprise_auth from "../enterprise_auth.js";
import type * as enterprise_autonomous from "../enterprise_autonomous.js";
import type * as enterprise_billing from "../enterprise_billing.js";
import type * as enterprise_client_payments from "../enterprise_client_payments.js";
import type * as enterprise_clients from "../enterprise_clients.js";
import type * as enterprise_companies from "../enterprise_companies.js";
import type * as enterprise_companion from "../enterprise_companion.js";
import type * as enterprise_emotional from "../enterprise_emotional.js";
import type * as enterprise_features from "../enterprise_features.js";
import type * as enterprise_knowledge from "../enterprise_knowledge.js";
import type * as enterprise_management from "../enterprise_management.js";
import type * as enterprise_marketplace from "../enterprise_marketplace.js";
import type * as enterprise_marketplace_templates from "../enterprise_marketplace_templates.js";
import type * as enterprise_payments from "../enterprise_payments.js";
import type * as enterprise_scaling from "../enterprise_scaling.js";
import type * as enterprise_security from "../enterprise_security.js";
import type * as enterprise_sla from "../enterprise_sla.js";
import type * as enterprise_subadmins from "../enterprise_subadmins.js";
import type * as enterprise_support from "../enterprise_support.js";
import type * as enterprise_workflows from "../enterprise_workflows.js";
import type * as event_agent from "../event_agent.js";
import type * as event_chat from "../event_chat.js";
import type * as exam_career_agent from "../exam_career_agent.js";
import type * as exam_career_chat from "../exam_career_chat.js";
import type * as exitIntent from "../exitIntent.js";
import type * as facebook_leads from "../facebook_leads.js";
import type * as feature_flags from "../feature_flags.js";
import type * as filegen_health from "../filegen_health.js";
import type * as finance_agent from "../finance_agent.js";
import type * as finance_chat from "../finance_chat.js";
import type * as finance_helpers from "../finance_helpers.js";
import type * as fintech from "../fintech.js";
import type * as flashSales from "../flashSales.js";
import type * as flyer_engine from "../flyer_engine.js";
import type * as flyer_posting from "../flyer_posting.js";
import type * as flyer_templates from "../flyer_templates.js";
import type * as gamification from "../gamification.js";
import type * as geo_blocking from "../geo_blocking.js";
import type * as geo_tracking from "../geo_tracking.js";
import type * as guardian from "../guardian.js";
import type * as guardian_watch from "../guardian_watch.js";
import type * as hermes_auto_install from "../hermes_auto_install.js";
import type * as hermes_gateway from "../hermes_gateway.js";
import type * as hermes_orchestrator from "../hermes_orchestrator.js";
import type * as holidays from "../holidays.js";
import type * as home_agent from "../home_agent.js";
import type * as home_chat from "../home_chat.js";
import type * as http from "../http.js";
import type * as image_management from "../image_management.js";
import type * as influencerRecruitment from "../influencerRecruitment.js";
import type * as init from "../init.js";
import type * as intrusion_detector from "../intrusion_detector.js";
import type * as invoice_generator from "../invoice_generator.js";
import type * as kdp_agent from "../kdp_agent.js";
import type * as kdp_constants from "../kdp_constants.js";
import type * as kdp_subscriptions from "../kdp_subscriptions.js";
import type * as knowledge_graph from "../knowledge_graph.js";
import type * as kora_checkout from "../kora_checkout.js";
import type * as kora_pay from "../kora_pay.js";
import type * as kora_webhook from "../kora_webhook.js";
import type * as landing_page from "../landing_page.js";
import type * as language_agent from "../language_agent.js";
import type * as language_chat from "../language_chat.js";
import type * as lead_scoring from "../lead_scoring.js";
import type * as leaderboard from "../leaderboard.js";
import type * as live_chats from "../live_chats.js";
import type * as live_feed from "../live_feed.js";
import type * as live_feeds from "../live_feeds.js";
import type * as loyalty_program from "../loyalty_program.js";
import type * as marketplace from "../marketplace.js";
import type * as mimo_core from "../mimo_core.js";
import type * as mobile_optimization from "../mobile_optimization.js";
import type * as model_analytics from "../model_analytics.js";
import type * as model_recovery from "../model_recovery.js";
import type * as model_toggle from "../model_toggle.js";
import type * as multi_language from "../multi_language.js";
import type * as opensource_generator from "../opensource_generator.js";
import type * as orchestration from "../orchestration.js";
import type * as order_management from "../order_management.js";
import type * as otp_email from "../otp_email.js";
import type * as password_management from "../password_management.js";
import type * as payment_enhancement from "../payment_enhancement.js";
import type * as payment_improvements from "../payment_improvements.js";
import type * as payments from "../payments.js";
import type * as payouts from "../payouts.js";
import type * as platformOAuth from "../platformOAuth.js";
import type * as platform_analytics from "../platform_analytics.js";
import type * as poster_converter from "../poster_converter.js";
import type * as poster_generator from "../poster_generator.js";
import type * as pre_subscription_handler from "../pre_subscription_handler.js";
import type * as pushNotifications from "../pushNotifications.js";
import type * as push_notifications from "../push_notifications.js";
import type * as qr_generator from "../qr_generator.js";
import type * as quick_setup from "../quick_setup.js";
import type * as rapidapi from "../rapidapi.js";
import type * as receipt_generator from "../receipt_generator.js";
import type * as receipts from "../receipts.js";
import type * as receipts_v2 from "../receipts_v2.js";
import type * as referral_system from "../referral_system.js";
import type * as referral_withdrawals from "../referral_withdrawals.js";
import type * as referrals from "../referrals.js";
import type * as reporting from "../reporting.js";
import type * as reports from "../reports.js";
import type * as revenue_credits from "../revenue_credits.js";
import type * as revenue_growth from "../revenue_growth.js";
import type * as revenue_marketplace from "../revenue_marketplace.js";
import type * as revenue_outcomes from "../revenue_outcomes.js";
import type * as revenue_social from "../revenue_social.js";
import type * as scheduledPosts from "../scheduledPosts.js";
import type * as schema_ad_engine from "../schema/ad_engine.js";
import type * as schema_agents from "../schema/agents.js";
import type * as schema_auto_heal from "../schema/auto_heal.js";
import type * as schema_composio from "../schema/composio.js";
import type * as schema_core from "../schema/core.js";
import type * as schema_enterprise from "../schema/enterprise.js";
import type * as schema_finance from "../schema/finance.js";
import type * as schema_gamification from "../schema/gamification.js";
import type * as schema_hermes from "../schema/hermes.js";
import type * as schema_index from "../schema/index.js";
import type * as schema_kdp from "../schema/kdp.js";
import type * as schema_marketplace from "../schema/marketplace.js";
import type * as schema_misc from "../schema/misc.js";
import type * as schema_notifications from "../schema/notifications.js";
import type * as schema_payments from "../schema/payments.js";
import type * as schema_security from "../schema/security.js";
import type * as schema_social from "../schema/social.js";
import type * as schema_trypost from "../schema/trypost.js";
import type * as schema_video from "../schema/video.js";
import type * as schema_whatsapp from "../schema/whatsapp.js";
import type * as secure_sweeps from "../secure_sweeps.js";
import type * as security_addon from "../security_addon.js";
import type * as seed from "../seed.js";
import type * as seed_admin from "../seed_admin.js";
import type * as seed_automation from "../seed_automation.js";
import type * as seed_companies from "../seed_companies.js";
import type * as seed_financials from "../seed_financials.js";
import type * as seed_kdp from "../seed_kdp.js";
import type * as seed_marketplace_templates from "../seed_marketplace_templates.js";
import type * as seed_migration from "../seed_migration.js";
import type * as seed_test from "../seed_test.js";
import type * as seoEngine from "../seoEngine.js";
import type * as shopping_agent from "../shopping_agent.js";
import type * as shopping_chat from "../shopping_chat.js";
import type * as sms_marketing from "../sms_marketing.js";
import type * as sms_notifications from "../sms_notifications.js";
import type * as social from "../social.js";
import type * as socialProof from "../socialProof.js";
import type * as social_proof from "../social_proof.js";
import type * as stripe_integration from "../stripe_integration.js";
import type * as subscription_guard from "../subscription_guard.js";
import type * as subscription_renewal from "../subscription_renewal.js";
import type * as support_orchestrator from "../support_orchestrator.js";
import type * as survey_commerce from "../survey_commerce.js";
import type * as synthetic_intelligence from "../synthetic_intelligence.js";
import type * as tax from "../tax.js";
import type * as teamAccounts from "../teamAccounts.js";
import type * as telegram_commerce from "../telegram_commerce.js";
import type * as test_telegram_post from "../test_telegram_post.js";
import type * as testimonials from "../testimonials.js";
import type * as tithe_deductions from "../tithe_deductions.js";
import type * as token_auto_renewal from "../token_auto_renewal.js";
import type * as token_refresh_proactive from "../token_refresh_proactive.js";
import type * as transfer_passkeys from "../transfer_passkeys.js";
import type * as translation_agent from "../translation_agent.js";
import type * as translation_chat from "../translation_chat.js";
import type * as travel_agent from "../travel_agent.js";
import type * as travel_chat from "../travel_chat.js";
import type * as trypost from "../trypost.js";
import type * as trypost_webhook from "../trypost_webhook.js";
import type * as uae_engine from "../uae_engine.js";
import type * as unifiedOrchestrator from "../unifiedOrchestrator.js";
import type * as unified_email from "../unified_email.js";
import type * as update_telegram_channel from "../update_telegram_channel.js";
import type * as updates from "../updates.js";
import type * as usage_alerts from "../usage_alerts.js";
import type * as usd_wallet from "../usd_wallet.js";
import type * as version_control from "../version_control.js";
import type * as video_agent from "../video_agent.js";
import type * as video_chat from "../video_chat.js";
import type * as video_generator from "../video_generator.js";
import type * as video_health from "../video_health.js";
import type * as video_production from "../video_production.js";
import type * as voice_roi from "../voice_roi.js";
import type * as webhook_notifications from "../webhook_notifications.js";
import type * as wellness_agent from "../wellness_agent.js";
import type * as wellness_chat from "../wellness_chat.js";
import type * as whatsapp_commerce from "../whatsapp_commerce.js";
import type * as whatsapp_dual from "../whatsapp_dual.js";
import type * as whatsapp_integration from "../whatsapp_integration.js";
import type * as whatsapp_openwa from "../whatsapp_openwa.js";
import type * as workflows from "../workflows.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  AwsEmailOTP: typeof AwsEmailOTP;
  TermiiOTP: typeof TermiiOTP;
  abandonedCheckouts: typeof abandonedCheckouts;
  academic_agent: typeof academic_agent;
  academic_chat: typeof academic_chat;
  adEngine: typeof adEngine;
  adOrchestrator: typeof adOrchestrator;
  ad_abtest: typeof ad_abtest;
  ad_alerts: typeof ad_alerts;
  ad_analytics_agg: typeof ad_analytics_agg;
  ad_auto_generator: typeof ad_auto_generator;
  ad_batch: typeof ad_batch;
  ad_budget: typeof ad_budget;
  ad_campaign_ai: typeof ad_campaign_ai;
  ad_compliance: typeof ad_compliance;
  ad_compliance_enhanced: typeof ad_compliance_enhanced;
  ad_compliance_precheck: typeof ad_compliance_precheck;
  ad_conversions: typeof ad_conversions;
  ad_dashboard: typeof ad_dashboard;
  ad_designer: typeof ad_designer;
  ad_monetization: typeof ad_monetization;
  ad_scheduling: typeof ad_scheduling;
  ad_webhooks: typeof ad_webhooks;
  admin: typeof admin;
  admin_auth: typeof admin_auth;
  admin_enterprise: typeof admin_enterprise;
  admin_enterprise_hub: typeof admin_enterprise_hub;
  admin_helpers: typeof admin_helpers;
  admin_payouts: typeof admin_payouts;
  affiliate_system: typeof affiliate_system;
  agent_analytics: typeof agent_analytics;
  agent_backups: typeof agent_backups;
  agent_marketplace: typeof agent_marketplace;
  agent_payments: typeof agent_payments;
  agent_performance: typeof agent_performance;
  agent_runtime: typeof agent_runtime;
  agent_tools: typeof agent_tools;
  agent_video_production: typeof agent_video_production;
  agentic_payments: typeof agentic_payments;
  "agents/chat_factory": typeof agents_chat_factory;
  "agents/config": typeof agents_config;
  "agents/registry": typeof agents_registry;
  ai_factory: typeof ai_factory;
  ai_image_generator: typeof ai_image_generator;
  ai_router: typeof ai_router;
  analytics_dashboard: typeof analytics_dashboard;
  api_costs: typeof api_costs;
  api_docs: typeof api_docs;
  appointment_booking: typeof appointment_booking;
  auth: typeof auth;
  auth_helpers: typeof auth_helpers;
  autoPosting: typeof autoPosting;
  auto_heal: typeof auto_heal;
  auto_healer: typeof auto_healer;
  aws_otp: typeof aws_otp;
  aws_sigv4: typeof aws_sigv4;
  bi_annual_upgrade: typeof bi_annual_upgrade;
  business_agent: typeof business_agent;
  business_chat: typeof business_chat;
  business_hours: typeof business_hours;
  cac_deductions: typeof cac_deductions;
  career_agent: typeof career_agent;
  career_chat: typeof career_chat;
  certification_agent: typeof certification_agent;
  certification_chat: typeof certification_chat;
  charity: typeof charity;
  chatbot: typeof chatbot;
  chatbotLeads: typeof chatbotLeads;
  classification: typeof classification;
  clientAnalytics: typeof clientAnalytics;
  client_2fa: typeof client_2fa;
  client_actions: typeof client_actions;
  client_history: typeof client_history;
  client_kyc: typeof client_kyc;
  client_payouts: typeof client_payouts;
  client_support: typeof client_support;
  client_wallet: typeof client_wallet;
  cloud_memory: typeof cloud_memory;
  communication: typeof communication;
  companion_agent: typeof companion_agent;
  composioClient: typeof composioClient;
  composioEnhanced: typeof composioEnhanced;
  composioEnhancement: typeof composioEnhancement;
  composioHub: typeof composioHub;
  composioToolkitDetails: typeof composioToolkitDetails;
  composio_admin: typeof composio_admin;
  content_agent: typeof content_agent;
  content_chat: typeof content_chat;
  credits: typeof credits;
  crm_hygiene: typeof crm_hygiene;
  crons: typeof crons;
  crossSell: typeof crossSell;
  crypto_pure: typeof crypto_pure;
  customer_database: typeof customer_database;
  customer_support: typeof customer_support;
  customer_support_bot: typeof customer_support_bot;
  dashboard: typeof dashboard;
  ecommerce: typeof ecommerce;
  emotional_ai: typeof emotional_ai;
  encryption: typeof encryption;
  "enterprise/org_admin": typeof enterprise_org_admin;
  "enterprise/org_bulk": typeof enterprise_org_bulk;
  "enterprise/org_crud": typeof enterprise_org_crud;
  "enterprise/org_transactions": typeof enterprise_org_transactions;
  enterprise_audit_logs: typeof enterprise_audit_logs;
  enterprise_auth: typeof enterprise_auth;
  enterprise_autonomous: typeof enterprise_autonomous;
  enterprise_billing: typeof enterprise_billing;
  enterprise_client_payments: typeof enterprise_client_payments;
  enterprise_clients: typeof enterprise_clients;
  enterprise_companies: typeof enterprise_companies;
  enterprise_companion: typeof enterprise_companion;
  enterprise_emotional: typeof enterprise_emotional;
  enterprise_features: typeof enterprise_features;
  enterprise_knowledge: typeof enterprise_knowledge;
  enterprise_management: typeof enterprise_management;
  enterprise_marketplace: typeof enterprise_marketplace;
  enterprise_marketplace_templates: typeof enterprise_marketplace_templates;
  enterprise_payments: typeof enterprise_payments;
  enterprise_scaling: typeof enterprise_scaling;
  enterprise_security: typeof enterprise_security;
  enterprise_sla: typeof enterprise_sla;
  enterprise_subadmins: typeof enterprise_subadmins;
  enterprise_support: typeof enterprise_support;
  enterprise_workflows: typeof enterprise_workflows;
  event_agent: typeof event_agent;
  event_chat: typeof event_chat;
  exam_career_agent: typeof exam_career_agent;
  exam_career_chat: typeof exam_career_chat;
  exitIntent: typeof exitIntent;
  facebook_leads: typeof facebook_leads;
  feature_flags: typeof feature_flags;
  filegen_health: typeof filegen_health;
  finance_agent: typeof finance_agent;
  finance_chat: typeof finance_chat;
  finance_helpers: typeof finance_helpers;
  fintech: typeof fintech;
  flashSales: typeof flashSales;
  flyer_engine: typeof flyer_engine;
  flyer_posting: typeof flyer_posting;
  flyer_templates: typeof flyer_templates;
  gamification: typeof gamification;
  geo_blocking: typeof geo_blocking;
  geo_tracking: typeof geo_tracking;
  guardian: typeof guardian;
  guardian_watch: typeof guardian_watch;
  hermes_auto_install: typeof hermes_auto_install;
  hermes_gateway: typeof hermes_gateway;
  hermes_orchestrator: typeof hermes_orchestrator;
  holidays: typeof holidays;
  home_agent: typeof home_agent;
  home_chat: typeof home_chat;
  http: typeof http;
  image_management: typeof image_management;
  influencerRecruitment: typeof influencerRecruitment;
  init: typeof init;
  intrusion_detector: typeof intrusion_detector;
  invoice_generator: typeof invoice_generator;
  kdp_agent: typeof kdp_agent;
  kdp_constants: typeof kdp_constants;
  kdp_subscriptions: typeof kdp_subscriptions;
  knowledge_graph: typeof knowledge_graph;
  kora_checkout: typeof kora_checkout;
  kora_pay: typeof kora_pay;
  kora_webhook: typeof kora_webhook;
  landing_page: typeof landing_page;
  language_agent: typeof language_agent;
  language_chat: typeof language_chat;
  lead_scoring: typeof lead_scoring;
  leaderboard: typeof leaderboard;
  live_chats: typeof live_chats;
  live_feed: typeof live_feed;
  live_feeds: typeof live_feeds;
  loyalty_program: typeof loyalty_program;
  marketplace: typeof marketplace;
  mimo_core: typeof mimo_core;
  mobile_optimization: typeof mobile_optimization;
  model_analytics: typeof model_analytics;
  model_recovery: typeof model_recovery;
  model_toggle: typeof model_toggle;
  multi_language: typeof multi_language;
  opensource_generator: typeof opensource_generator;
  orchestration: typeof orchestration;
  order_management: typeof order_management;
  otp_email: typeof otp_email;
  password_management: typeof password_management;
  payment_enhancement: typeof payment_enhancement;
  payment_improvements: typeof payment_improvements;
  payments: typeof payments;
  payouts: typeof payouts;
  platformOAuth: typeof platformOAuth;
  platform_analytics: typeof platform_analytics;
  poster_converter: typeof poster_converter;
  poster_generator: typeof poster_generator;
  pre_subscription_handler: typeof pre_subscription_handler;
  pushNotifications: typeof pushNotifications;
  push_notifications: typeof push_notifications;
  qr_generator: typeof qr_generator;
  quick_setup: typeof quick_setup;
  rapidapi: typeof rapidapi;
  receipt_generator: typeof receipt_generator;
  receipts: typeof receipts;
  receipts_v2: typeof receipts_v2;
  referral_system: typeof referral_system;
  referral_withdrawals: typeof referral_withdrawals;
  referrals: typeof referrals;
  reporting: typeof reporting;
  reports: typeof reports;
  revenue_credits: typeof revenue_credits;
  revenue_growth: typeof revenue_growth;
  revenue_marketplace: typeof revenue_marketplace;
  revenue_outcomes: typeof revenue_outcomes;
  revenue_social: typeof revenue_social;
  scheduledPosts: typeof scheduledPosts;
  "schema/ad_engine": typeof schema_ad_engine;
  "schema/agents": typeof schema_agents;
  "schema/auto_heal": typeof schema_auto_heal;
  "schema/composio": typeof schema_composio;
  "schema/core": typeof schema_core;
  "schema/enterprise": typeof schema_enterprise;
  "schema/finance": typeof schema_finance;
  "schema/gamification": typeof schema_gamification;
  "schema/hermes": typeof schema_hermes;
  "schema/index": typeof schema_index;
  "schema/kdp": typeof schema_kdp;
  "schema/marketplace": typeof schema_marketplace;
  "schema/misc": typeof schema_misc;
  "schema/notifications": typeof schema_notifications;
  "schema/payments": typeof schema_payments;
  "schema/security": typeof schema_security;
  "schema/social": typeof schema_social;
  "schema/trypost": typeof schema_trypost;
  "schema/video": typeof schema_video;
  "schema/whatsapp": typeof schema_whatsapp;
  secure_sweeps: typeof secure_sweeps;
  security_addon: typeof security_addon;
  seed: typeof seed;
  seed_admin: typeof seed_admin;
  seed_automation: typeof seed_automation;
  seed_companies: typeof seed_companies;
  seed_financials: typeof seed_financials;
  seed_kdp: typeof seed_kdp;
  seed_marketplace_templates: typeof seed_marketplace_templates;
  seed_migration: typeof seed_migration;
  seed_test: typeof seed_test;
  seoEngine: typeof seoEngine;
  shopping_agent: typeof shopping_agent;
  shopping_chat: typeof shopping_chat;
  sms_marketing: typeof sms_marketing;
  sms_notifications: typeof sms_notifications;
  social: typeof social;
  socialProof: typeof socialProof;
  social_proof: typeof social_proof;
  stripe_integration: typeof stripe_integration;
  subscription_guard: typeof subscription_guard;
  subscription_renewal: typeof subscription_renewal;
  support_orchestrator: typeof support_orchestrator;
  survey_commerce: typeof survey_commerce;
  synthetic_intelligence: typeof synthetic_intelligence;
  tax: typeof tax;
  teamAccounts: typeof teamAccounts;
  telegram_commerce: typeof telegram_commerce;
  test_telegram_post: typeof test_telegram_post;
  testimonials: typeof testimonials;
  tithe_deductions: typeof tithe_deductions;
  token_auto_renewal: typeof token_auto_renewal;
  token_refresh_proactive: typeof token_refresh_proactive;
  transfer_passkeys: typeof transfer_passkeys;
  translation_agent: typeof translation_agent;
  translation_chat: typeof translation_chat;
  travel_agent: typeof travel_agent;
  travel_chat: typeof travel_chat;
  trypost: typeof trypost;
  trypost_webhook: typeof trypost_webhook;
  uae_engine: typeof uae_engine;
  unifiedOrchestrator: typeof unifiedOrchestrator;
  unified_email: typeof unified_email;
  update_telegram_channel: typeof update_telegram_channel;
  updates: typeof updates;
  usage_alerts: typeof usage_alerts;
  usd_wallet: typeof usd_wallet;
  version_control: typeof version_control;
  video_agent: typeof video_agent;
  video_chat: typeof video_chat;
  video_generator: typeof video_generator;
  video_health: typeof video_health;
  video_production: typeof video_production;
  voice_roi: typeof voice_roi;
  webhook_notifications: typeof webhook_notifications;
  wellness_agent: typeof wellness_agent;
  wellness_chat: typeof wellness_chat;
  whatsapp_commerce: typeof whatsapp_commerce;
  whatsapp_dual: typeof whatsapp_dual;
  whatsapp_integration: typeof whatsapp_integration;
  whatsapp_openwa: typeof whatsapp_openwa;
  workflows: typeof workflows;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  agent: import("@convex-dev/agent/_generated/component.js").ComponentApi<"agent">;
};
