import { motion } from 'framer-motion';
import { Shield, Cpu, Globe, CheckCircle, Lock, Zap, Target, Eye, Heart, Award, TrendingUp, Users, Rocket } from 'lucide-react';
import { securityLayers } from '../data/agents';

export default function AboutPage() {
  return (
    <section className="py-24 bg-cream min-h-screen">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Hero Header */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="text-center mb-16">
          <img src="/images/dutchkem-logo.png" alt="Dutchkem Ventures" className="w-28 h-28 object-contain mx-auto mb-6 drop-shadow-xl rounded-xl" />
          <h2 className="font-display text-3xl sm:text-4xl lg:text-5xl font-bold text-navy">
            We Don't Just Offer Services.<br />
            <span className="text-coral">We Solve Problems.</span>
          </h2>
          <p className="mt-6 text-navy/60 text-lg max-w-3xl mx-auto leading-relaxed">
            Dutchkem Ventures ProSuite NG+ is Nigeria's first unified AI platform with 13 specialized agents. 
            We exist because too many Nigerians spend weeks chasing what should take hours — writing a thesis, 
            processing a visa, recovering a stolen phone, or building a business plan. We built an army of AI 
            agents to handle it all, so you can focus on what matters most.
          </p>
        </motion.div>

        {/* Vision & Mission */}
        <div className="grid md:grid-cols-2 gap-6 mb-16">
          <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.1 }}
            className="bg-gradient-to-br from-navy to-navy-dark rounded-3xl p-8 text-white relative overflow-hidden">
            <div className="absolute top-0 right-0 w-40 h-40 bg-coral/10 rounded-full blur-3xl" />
            <div className="relative z-10">
              <div className="w-14 h-14 rounded-2xl bg-coral/20 flex items-center justify-center mb-5">
                <Eye size={28} className="text-coral-light" />
              </div>
              <h3 className="font-display text-2xl font-bold mb-4">Our Vision</h3>
              <p className="text-white/70 text-lg leading-relaxed">
                To become Africa's most trusted AI-powered service platform — where every Nigerian, 
                regardless of location, income, or technical ability, can access world-class professional 
                services at the tap of a button. We envision a Nigeria where a student in Maiduguri gets the 
                same quality thesis support as one in Lagos, and an entrepreneur in Sokoto can access the same 
                business tools as one in Silicon Valley.
              </p>
            </div>
          </motion.div>

          <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.2 }}
            className="bg-gradient-to-br from-forest to-forest-dark rounded-3xl p-8 text-white relative overflow-hidden">
            <div className="absolute bottom-0 left-0 w-40 h-40 bg-gold/10 rounded-full blur-3xl" />
            <div className="relative z-10">
              <div className="w-14 h-14 rounded-2xl bg-gold/20 flex items-center justify-center mb-5">
                <Target size={28} className="text-gold" />
              </div>
              <h3 className="font-display text-2xl font-bold mb-4">Our Mission</h3>
              <p className="text-white/70 text-lg leading-relaxed">
                To empower 10 million Nigerians by 2030 with AI-driven solutions that eliminate 
                the stress, cost, and delays of professional services. We deploy cutting-edge technology 
                — including NVIDIA's most powerful AI models — to deliver results that are faster, cheaper, 
                and better than traditional alternatives. Every service we offer comes with a satisfaction 
                guarantee, because we don't succeed until you do.
              </p>
            </div>
          </motion.div>
        </div>

        {/* Why Dutchkem */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }} className="mb-16">
          <h3 className="font-display text-2xl sm:text-3xl font-bold text-navy text-center mb-10">
            Why <span className="text-coral">10,000+ Nigerians</span> Trust Dutchkem
          </h3>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {[
              { icon: <Cpu size={28} />, title: 'Real AI, Not Templates', desc: 'Every response is generated by NVIDIA\'s Llama 3.3 70B model — the same AI powering Silicon Valley startups. No copy-paste templates, no recycled content. Your work is 100% original, every time.', color: 'bg-electric/10 text-electric' },
              { icon: <Zap size={28} />, title: 'Speed That Saves You', desc: 'What takes a freelancer 5 days takes our AI 5 hours. We\'ve helped students submit assignments 48 hours before deadline, and businesses launch with pitch decks built overnight. Time is money — we save you both.', color: 'bg-gold/10 text-gold-dark' },
              { icon: <Shield size={28} />, title: 'Bank-Grade Security', desc: '18 layers of protection guard your data — AES-256 encryption, MFA authentication, ClamAV virus scanning, and immutable audit logs. Your documents, payments, and conversations are safer here than in your email.', color: 'bg-coral/10 text-coral' },
              { icon: <Globe size={28} />, title: 'Nationwide, 24/7', desc: 'Whether you\'re in Lagos, Kano, Enugu, or Maiduguri — our 13 agents work around the clock. No office visits, no appointments, no waiting rooms. Just open your phone and get it done.', color: 'bg-forest/10 text-forest' },
              { icon: <Award size={28} />, title: '2 Free Revisions', desc: 'We stand behind our work. Every service includes 2 free revisions — no questions asked. Over 95% of clients are satisfied on the first delivery. We don\'t stop until you\'re happy.', color: 'bg-purple-100 text-purple-600' },
              { icon: <Heart size={28} />, title: 'Built FOR Nigeria', desc: 'We understand pidgin, we know WAEC scoring, we speak Yoruba pricing. Our agents understand Nigerian universities, Nigerian immigration pathways, and Nigerian business regulations because we built them that way.', color: 'bg-pink-100 text-pink-600' },
            ].map((card, i) => (
              <motion.div key={i} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 + i * 0.05 }}
                className="bg-white rounded-3xl p-7 border border-gray-100 hover:shadow-xl transition-all">
                <div className={`w-14 h-14 rounded-2xl ${card.color} flex items-center justify-center mb-5`}>{card.icon}</div>
                <h4 className="font-display text-lg font-bold text-navy mb-3">{card.title}</h4>
                <p className="text-navy/60 text-sm leading-relaxed">{card.desc}</p>
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* The Numbers */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.25 }}
          className="bg-gradient-to-r from-navy via-navy-dark to-navy rounded-3xl p-8 lg:p-12 text-white mb-16">
          <h3 className="font-display text-2xl font-bold text-center mb-8">The Numbers Don't Lie</h3>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-6">
            {[
              { value: '10,000+', label: 'Clients Served', icon: <Users size={20} /> },
              { value: '₦2B+', label: 'Value Delivered', icon: <TrendingUp size={20} /> },
              { value: '4.9/5', label: 'Client Rating', icon: <Award size={20} /> },
              { value: '13', label: 'AI Agents Live', icon: <Rocket size={20} /> },
            ].map((stat, i) => (
              <div key={i} className="text-center">
                <div className="w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center mx-auto mb-3 text-gold">{stat.icon}</div>
                <p className="font-display text-3xl lg:text-4xl font-bold text-gold">{stat.value}</p>
                <p className="text-white/50 text-sm mt-1">{stat.label}</p>
              </div>
            ))}
          </div>
        </motion.div>

        {/* AI Engine */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }} className="mb-16">
          <h3 className="font-display text-2xl font-bold text-navy text-center mb-8">🤖 Powered by the Best AI in the World</h3>
          <div className="grid md:grid-cols-2 gap-6">
            {[
              { model: 'meta/llama-3.3-70b-instruct', role: '11 Agents — Academic, Business, Legal, Immigration', specs: ['70 billion parameters', 'Latest Meta AI model', 'Top-tier reasoning', 'Trained on trillions of tokens'], icon: <Cpu size={20} /> },
              { model: 'mistralai/mixtral-8x22b-instruct', role: 'MediaStudio — Multilingual Content & Translation', specs: ['176B parameters (MoE)', 'Yoruba, Hausa, Igbo, Pidgin', 'Creative writing mastery', 'Handles 50+ languages'], icon: <Globe size={20} /> },
            ].map((ai, i) => (
              <div key={i} className="bg-white rounded-2xl p-6 border border-gray-100">
                <div className="flex items-center gap-3 mb-3">
                  <div className="w-9 h-9 rounded-lg bg-electric/10 flex items-center justify-center text-electric">{ai.icon}</div>
                  <div><p className="font-mono text-xs text-coral">{ai.model}</p><p className="text-sm font-medium text-navy">{ai.role}</p></div>
                </div>
                <div className="flex flex-wrap gap-1.5 mt-2">
                  {ai.specs.map((spec, j) => (<span key={j} className="px-2 py-1 bg-cream rounded-md text-xs text-navy/60">{spec}</span>))}
                </div>
              </div>
            ))}
          </div>
        </motion.div>

        {/* Security Layers */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.35 }} className="mb-16">
          <h3 className="font-display text-2xl font-bold text-navy text-center mb-8">🔒 18-Layer Security Architecture</h3>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {securityLayers.map((layer, i) => (
              <motion.div key={i} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * 0.02 }}
                className="bg-white rounded-xl p-4 border border-gray-100 flex items-center gap-3 hover:border-forest/30 hover:shadow-md transition-all">
                <div className="w-8 h-8 rounded-lg bg-forest/10 flex items-center justify-center shrink-0"><Lock size={14} className="text-forest" /></div>
                <div>
                  <span className="font-mono text-[10px] text-navy/30">Layer {i + 1}</span>
                  <p className="text-sm text-navy font-medium">{layer}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* Coverage */}
        <div className="grid md:grid-cols-2 gap-6 mb-16">
          <div className="bg-white rounded-3xl p-8 border border-gray-100">
            <h3 className="font-display text-xl font-bold text-navy mb-6 flex items-center gap-2">🗺️ Coverage — Nationwide Nigeria</h3>
            <div className="grid grid-cols-3 gap-3">
              {['Lagos', 'Abuja', 'Kano', 'Port Harcourt', 'Ibadan', 'Enugu', 'Benin City', 'Kaduna', 'All 36 States + FCT'].map((state) => (
                <div key={state} className="flex items-center gap-2 p-3 bg-cream rounded-xl">
                  <CheckCircle size={14} className="text-forest shrink-0" />
                  <span className="text-xs font-medium text-navy">{state}</span>
                </div>
              ))}
            </div>
          </div>
          <div className="bg-white rounded-3xl p-8 border border-gray-100">
            <h3 className="font-display text-xl font-bold text-navy mb-6 flex items-center gap-2">📊 Platform Stats</h3>
            <div className="grid grid-cols-2 gap-4">
              {[
                { label: 'AI Agents', value: '13' }, { label: 'Features', value: '200+' },
                { label: 'API Integrations', value: '35+' }, { label: 'Security Layers', value: '18' },
                { label: 'Languages', value: '50+' }, { label: 'Delivery Formats', value: '12' },
              ].map((stat, i) => (
                <div key={i} className="text-center p-3 bg-cream rounded-xl">
                  <p className="font-display text-2xl font-bold text-coral">{stat.value}</p>
                  <p className="text-xs text-navy/50 mt-1">{stat.label}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* APIs */}
        <div className="bg-white rounded-3xl p-8 border border-gray-100 mb-16">
          <h3 className="font-display text-xl font-bold text-navy mb-6 flex items-center gap-2">🔗 35+ Integrated APIs</h3>
          <div className="flex flex-wrap gap-2">
            {['NVIDIA NIM','Llama 3.3 70B','Mixtral 8x22B','Whisper API','ElevenLabs','Google Translate','DeepL','FFmpeg','Google Maps','NIMC NIN','NIBSS BVN','NCC','FRSC','ExcelJS','Power BI','Wolfram Alpha','Crossref','Semantic Scholar','arXiv','Canva','TikTok API','Facebook Graph','Buffer','Gmail API','Google Calendar','QuickBooks','DocuSign','CAC API','Termii','SendGrid','ClamAV','Redis','Cloudinary'].map((api, i) => (
              <span key={i} className="px-3 py-1.5 bg-cream rounded-lg text-xs font-medium text-navy/60 border border-gray-100 hover:border-electric/30 hover:text-electric transition-colors">{api}</span>
            ))}
          </div>
        </div>

        {/* CTA */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }} className="text-center">
          <div className="bg-gradient-to-br from-coral/5 to-gold/5 rounded-3xl p-8 lg:p-12 border border-coral/10">
            <img src="/images/dutchkem-logo.png" alt="Dutchkem Ventures" className="w-16 h-16 object-contain mx-auto mb-4 rounded-lg" />
            <h3 className="font-display text-2xl font-bold text-navy mb-3">Built with ❤️ for Nigeria</h3>
            <p className="text-navy/60 max-w-2xl mx-auto">
              We're not just a tech company. We're Nigerians building for Nigerians. Every agent, 
              every feature, every line of code was designed with one question: "Will this make life easier 
              for someone in Nigeria today?" If you've read this far, you already know the answer.
            </p>
            <p className="mt-4 font-display text-lg text-coral/60 italic">
              "Your academic success, business growth, and professional services handled with care."
            </p>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
