import ePub from 'epub-gen';

export async function generateEpub(title, author, content, outputPath) {
  const options = {
    title,
    author,
    output: outputPath,
    content: [
      {
        title: title,
        data: `<h1 style="text-align:center;font-family:Georgia,serif;font-size:28px;color:#800000;margin-bottom:20px;">${title}</h1>
<p style="text-align:center;font-family:Georgia,serif;font-size:14px;color:#666;margin-bottom:40px;">by ${author}</p>
<hr style="border:1px solid #D4AF37;margin:30px auto;width:50%;"/>
${content.split('\n\n').map(p => `<p style="font-family:Georgia,serif;font-size:12pt;line-height:1.8;text-indent:1.5em;margin:0.8em 0;text-align:justify;">${p.replace(/\n/g, '<br/>')}</p>`).join('\n')}`,
      },
    ],
  };
  return await ePub(options);
}

export function generatePdfContent(manuscript) {
  const title = typeof manuscript === 'object' ? (manuscript.title || 'Untitled') : 'Generated Content';
  const author = typeof manuscript === 'object' ? (manuscript.author || manuscript.authorName || 'Dutchkem Ventures') : 'Dutchkem Ventures';
  const content = typeof manuscript === 'object' ? (manuscript.content || manuscript.body || '') : manuscript;
  const escaped = content.replace(/</g, '&lt;').replace(/>/g, '&gt;');
  
  const paragraphs = escaped.split('\n\n').map(p => 
    `<p style="font-family:Georgia,'Times New Roman',serif;font-size:12pt;line-height:1.8;text-indent:1.5em;margin:0.8em 0;text-align:justify;color:#1a1a1a;">${p.replace(/\n/g, '<br/>')}</p>`
  ).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} — Dutchkem Ventures</title>
  <style>
    @page { margin: 1in; size: A4; }
    @page :first { margin-top: 2in; }
    body { font-family: Georgia, 'Times New Roman', serif; max-width: 650px; margin: 0 auto; padding: 60px 40px; line-height: 1.8; color: #1a1a1a; background: white; }
    .cover { text-align: center; padding: 100px 0 60px; border-bottom: 3px double #D4AF37; margin-bottom: 40px; }
    .cover h1 { font-size: 32px; color: #800000; margin-bottom: 10px; letter-spacing: -0.5px; }
    .cover .author { font-size: 16px; color: #666; font-style: italic; }
    .cover .brand { font-size: 11px; color: #999; text-transform: uppercase; letter-spacing: 3px; margin-top: 30px; }
    h2 { font-size: 20px; color: #800000; border-bottom: 2px solid #D4AF37; padding-bottom: 8px; margin: 40px 0 20px; }
    .footer { text-align: center; font-size: 9px; color: #999; text-transform: uppercase; letter-spacing: 2px; margin-top: 60px; padding-top: 20px; border-top: 1px solid #eee; }
  </style>
</head>
<body>
  <div class="cover">
    <h1>${title}</h1>
    <p class="author">by ${author}</p>
    <p class="brand">Dutchkem Ventures ProSuite NG+</p>
  </div>
  ${paragraphs}
  <div class="footer">
    <p>Generated by Dutchkem Ventures ProSuite NG+</p>
    <p>RC: 9489855 • contact@dutchkem.com</p>
  </div>
</body>
</html>`;
}

export function generateExcelContent(data, title) {
  const headers = data.length > 0 ? Object.keys(data[0]) : [];
  return `<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
  <Styles>
    <Style ss:ID="header"><Font ss:Bold="1" ss:Size="11" ss:Color="#FFFFFF"/><Interior ss:Color="#800000" ss:Pattern="Solid"/></Style>
    <Style ss:ID="data"><Font ss:Size="10"/><Alignment ss:Vertical="Center"/></Style>
  </Styles>
  <Worksheet ss:Name="${title}">
    <Table>
      <Row>${headers.map(h => `<Cell ss:StyleID="header"><Data ss:Type="String">${h}</Data></Cell>`).join('')}</Row>
      ${data.map(row => `<Row>${headers.map(h => `<Cell ss:StyleID="data"><Data ss:Type="String">${row[h] || ''}</Data></Cell>`).join('')}</Row>`).join('\n      ')}
    </Table>
  </Worksheet>
</Workbook>`;
}

export function generateWordContent(title, content, author) {
  return `<!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">
<head>
  <meta charset="utf-8">
  <title>${title}</title>
  <style>
    body { font-family: Calibri, sans-serif; font-size: 11pt; line-height: 1.5; margin: 1in; color: #333; }
    h1 { font-size: 24pt; color: #800000; border-bottom: 2pt solid #D4AF37; padding-bottom: 8pt; }
    h2 { font-size: 16pt; color: #800000; margin-top: 24pt; }
    .header { text-align: center; margin-bottom: 30pt; padding-bottom: 20pt; border-bottom: 1pt solid #ccc; }
    .footer { text-align: center; font-size: 9pt; color: #999; margin-top: 40pt; padding-top: 15pt; border-top: 1pt solid #ccc; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${title}</h1>
    <p>by ${author || 'Dutchkem Ventures'}</p>
  </div>
  ${content.split('\n\n').map(p => `<p>${p.replace(/\n/g, '<br/>')}</p>`).join('')}
  <div class="footer">
    <p>Generated by Dutchkem Ventures ProSuite NG+ | RC: 9489855</p>
  </div>
</body>
</html>`;
}

export function generatePowerPointContent(title, slides) {
  return `<?xml version="1.0"?>
<presentation xmlns="http://schemas.microsoft.com/office/powerpoint/2006/main">
  ${slides.map((slide, i) => `
  <sld id="${i + 1}">
    <cSld>
      <spTree>
        <sp>
          <txBody>
            <p><r><rPr><b/><sz val="36"/><solidFill><srgbClr val="800000"/></solidFill></rPr><t>${slide.title || `Slide ${i + 1}`}</t></r></p>
          </txBody>
        </sp>
        <sp>
          <txBody>
            <p><r><t>${slide.content || ''}</t></r></p>
          </txBody>
        </sp>
      </spTree>
    </cSld>
  </sld>`).join('')}
</presentation>`;
}

export function generateMobiContent(epubBuffer) {
  // MOBI generation requires kindlegen or calibre CLI in production.
  return epubBuffer;
}
