/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WellnessCoachRouteImport } from './routes/wellness-coach'
import { Route as VideoProductionRouteImport } from './routes/video-production'
import { Route as TravelPlannerRouteImport } from './routes/travel-planner'
import { Route as TranslationHubRouteImport } from './routes/translation-hub'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PersonalShopperRouteImport } from './routes/personal-shopper'
import { Route as LanguageCoachRouteImport } from './routes/language-coach'
import { Route as HomeManagementRouteImport } from './routes/home-management'
import { Route as FinanceAdvisorRouteImport } from './routes/finance-advisor'
import { Route as ExamSuccessRouteImport } from './routes/exam-success'
import { Route as ExamPrepRouteImport } from './routes/exam-prep'
import { Route as EventPlannerRouteImport } from './routes/event-planner'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContentWriterRouteImport } from './routes/content-writer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CareerCoachRouteImport } from './routes/career-coach'
import { Route as BusinessConsultantRouteImport } from './routes/business-consultant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AllAgentsRouteImport } from './routes/all-agents'
import { Route as AcademicWriterRouteImport } from './routes/academic-writer'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnterpriseLoginRouteImport } from './routes/enterprise/login'
import { Route as EnterpriseDashboardRouteImport } from './routes/enterprise/dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'

const WellnessCoachRoute = WellnessCoachRouteImport.update({
  id: '/wellness-coach',
  path: '/wellness-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoProductionRoute = VideoProductionRouteImport.update({
  id: '/video-production',
  path: '/video-production',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelPlannerRoute = TravelPlannerRouteImport.update({
  id: '/travel-planner',
  path: '/travel-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslationHubRoute = TranslationHubRouteImport.update({
  id: '/translation-hub',
  path: '/translation-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalShopperRoute = PersonalShopperRouteImport.update({
  id: '/personal-shopper',
  path: '/personal-shopper',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageCoachRoute = LanguageCoachRouteImport.update({
  id: '/language-coach',
  path: '/language-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeManagementRoute = HomeManagementRouteImport.update({
  id: '/home-management',
  path: '/home-management',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceAdvisorRoute = FinanceAdvisorRouteImport.update({
  id: '/finance-advisor',
  path: '/finance-advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamSuccessRoute = ExamSuccessRouteImport.update({
  id: '/exam-success',
  path: '/exam-success',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamPrepRoute = ExamPrepRouteImport.update({
  id: '/exam-prep',
  path: '/exam-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const EventPlannerRoute = EventPlannerRouteImport.update({
  id: '/event-planner',
  path: '/event-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentWriterRoute = ContentWriterRouteImport.update({
  id: '/content-writer',
  path: '/content-writer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerCoachRoute = CareerCoachRouteImport.update({
  id: '/career-coach',
  path: '/career-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessConsultantRoute = BusinessConsultantRouteImport.update({
  id: '/business-consultant',
  path: '/business-consultant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AllAgentsRoute = AllAgentsRouteImport.update({
  id: '/all-agents',
  path: '/all-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicWriterRoute = AcademicWriterRouteImport.update({
  id: '/academic-writer',
  path: '/academic-writer',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseLoginRoute = EnterpriseLoginRouteImport.update({
  id: '/enterprise/login',
  path: '/enterprise/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseDashboardRoute = EnterpriseDashboardRouteImport.update({
  id: '/enterprise/dashboard',
  path: '/enterprise/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-writer': typeof AcademicWriterRoute
  '/all-agents': typeof AllAgentsRoute
  '/auth': typeof AuthRoute
  '/business-consultant': typeof BusinessConsultantRoute
  '/career-coach': typeof CareerCoachRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/content-writer': typeof ContentWriterRoute
  '/dashboard': typeof DashboardRoute
  '/event-planner': typeof EventPlannerRoute
  '/exam-prep': typeof ExamPrepRoute
  '/exam-success': typeof ExamSuccessRoute
  '/finance-advisor': typeof FinanceAdvisorRoute
  '/home-management': typeof HomeManagementRoute
  '/language-coach': typeof LanguageCoachRoute
  '/personal-shopper': typeof PersonalShopperRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/translation-hub': typeof TranslationHubRoute
  '/travel-planner': typeof TravelPlannerRoute
  '/video-production': typeof VideoProductionRoute
  '/wellness-coach': typeof WellnessCoachRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/enterprise/dashboard': typeof EnterpriseDashboardRoute
  '/enterprise/login': typeof EnterpriseLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-writer': typeof AcademicWriterRoute
  '/all-agents': typeof AllAgentsRoute
  '/auth': typeof AuthRoute
  '/business-consultant': typeof BusinessConsultantRoute
  '/career-coach': typeof CareerCoachRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/content-writer': typeof ContentWriterRoute
  '/dashboard': typeof DashboardRoute
  '/event-planner': typeof EventPlannerRoute
  '/exam-prep': typeof ExamPrepRoute
  '/exam-success': typeof ExamSuccessRoute
  '/finance-advisor': typeof FinanceAdvisorRoute
  '/home-management': typeof HomeManagementRoute
  '/language-coach': typeof LanguageCoachRoute
  '/personal-shopper': typeof PersonalShopperRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/translation-hub': typeof TranslationHubRoute
  '/travel-planner': typeof TravelPlannerRoute
  '/video-production': typeof VideoProductionRoute
  '/wellness-coach': typeof WellnessCoachRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/enterprise/dashboard': typeof EnterpriseDashboardRoute
  '/enterprise/login': typeof EnterpriseLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-writer': typeof AcademicWriterRoute
  '/all-agents': typeof AllAgentsRoute
  '/auth': typeof AuthRoute
  '/business-consultant': typeof BusinessConsultantRoute
  '/career-coach': typeof CareerCoachRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/content-writer': typeof ContentWriterRoute
  '/dashboard': typeof DashboardRoute
  '/event-planner': typeof EventPlannerRoute
  '/exam-prep': typeof ExamPrepRoute
  '/exam-success': typeof ExamSuccessRoute
  '/finance-advisor': typeof FinanceAdvisorRoute
  '/home-management': typeof HomeManagementRoute
  '/language-coach': typeof LanguageCoachRoute
  '/personal-shopper': typeof PersonalShopperRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/translation-hub': typeof TranslationHubRoute
  '/travel-planner': typeof TravelPlannerRoute
  '/video-production': typeof VideoProductionRoute
  '/wellness-coach': typeof WellnessCoachRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/enterprise/dashboard': typeof EnterpriseDashboardRoute
  '/enterprise/login': typeof EnterpriseLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academic-writer'
    | '/all-agents'
    | '/auth'
    | '/business-consultant'
    | '/career-coach'
    | '/careers'
    | '/contact'
    | '/content-writer'
    | '/dashboard'
    | '/event-planner'
    | '/exam-prep'
    | '/exam-success'
    | '/finance-advisor'
    | '/home-management'
    | '/language-coach'
    | '/personal-shopper'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/translation-hub'
    | '/travel-planner'
    | '/video-production'
    | '/wellness-coach'
    | '/admin/dashboard'
    | '/admin/login'
    | '/enterprise/dashboard'
    | '/enterprise/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academic-writer'
    | '/all-agents'
    | '/auth'
    | '/business-consultant'
    | '/career-coach'
    | '/careers'
    | '/contact'
    | '/content-writer'
    | '/dashboard'
    | '/event-planner'
    | '/exam-prep'
    | '/exam-success'
    | '/finance-advisor'
    | '/home-management'
    | '/language-coach'
    | '/personal-shopper'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/translation-hub'
    | '/travel-planner'
    | '/video-production'
    | '/wellness-coach'
    | '/admin/dashboard'
    | '/admin/login'
    | '/enterprise/dashboard'
    | '/enterprise/login'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academic-writer'
    | '/all-agents'
    | '/auth'
    | '/business-consultant'
    | '/career-coach'
    | '/careers'
    | '/contact'
    | '/content-writer'
    | '/dashboard'
    | '/event-planner'
    | '/exam-prep'
    | '/exam-success'
    | '/finance-advisor'
    | '/home-management'
    | '/language-coach'
    | '/personal-shopper'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/translation-hub'
    | '/travel-planner'
    | '/video-production'
    | '/wellness-coach'
    | '/admin/dashboard'
    | '/admin/login'
    | '/enterprise/dashboard'
    | '/enterprise/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicWriterRoute: typeof AcademicWriterRoute
  AllAgentsRoute: typeof AllAgentsRoute
  AuthRoute: typeof AuthRoute
  BusinessConsultantRoute: typeof BusinessConsultantRoute
  CareerCoachRoute: typeof CareerCoachRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  ContentWriterRoute: typeof ContentWriterRoute
  DashboardRoute: typeof DashboardRoute
  EventPlannerRoute: typeof EventPlannerRoute
  ExamPrepRoute: typeof ExamPrepRoute
  ExamSuccessRoute: typeof ExamSuccessRoute
  FinanceAdvisorRoute: typeof FinanceAdvisorRoute
  HomeManagementRoute: typeof HomeManagementRoute
  LanguageCoachRoute: typeof LanguageCoachRoute
  PersonalShopperRoute: typeof PersonalShopperRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  TranslationHubRoute: typeof TranslationHubRoute
  TravelPlannerRoute: typeof TravelPlannerRoute
  VideoProductionRoute: typeof VideoProductionRoute
  WellnessCoachRoute: typeof WellnessCoachRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  EnterpriseDashboardRoute: typeof EnterpriseDashboardRoute
  EnterpriseLoginRoute: typeof EnterpriseLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wellness-coach': {
      id: '/wellness-coach'
      path: '/wellness-coach'
      fullPath: '/wellness-coach'
      preLoaderRoute: typeof WellnessCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-production': {
      id: '/video-production'
      path: '/video-production'
      fullPath: '/video-production'
      preLoaderRoute: typeof VideoProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-planner': {
      id: '/travel-planner'
      path: '/travel-planner'
      fullPath: '/travel-planner'
      preLoaderRoute: typeof TravelPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translation-hub': {
      id: '/translation-hub'
      path: '/translation-hub'
      fullPath: '/translation-hub'
      preLoaderRoute: typeof TranslationHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-shopper': {
      id: '/personal-shopper'
      path: '/personal-shopper'
      fullPath: '/personal-shopper'
      preLoaderRoute: typeof PersonalShopperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language-coach': {
      id: '/language-coach'
      path: '/language-coach'
      fullPath: '/language-coach'
      preLoaderRoute: typeof LanguageCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-management': {
      id: '/home-management'
      path: '/home-management'
      fullPath: '/home-management'
      preLoaderRoute: typeof HomeManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-advisor': {
      id: '/finance-advisor'
      path: '/finance-advisor'
      fullPath: '/finance-advisor'
      preLoaderRoute: typeof FinanceAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-success': {
      id: '/exam-success'
      path: '/exam-success'
      fullPath: '/exam-success'
      preLoaderRoute: typeof ExamSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-prep': {
      id: '/exam-prep'
      path: '/exam-prep'
      fullPath: '/exam-prep'
      preLoaderRoute: typeof ExamPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-planner': {
      id: '/event-planner'
      path: '/event-planner'
      fullPath: '/event-planner'
      preLoaderRoute: typeof EventPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-writer': {
      id: '/content-writer'
      path: '/content-writer'
      fullPath: '/content-writer'
      preLoaderRoute: typeof ContentWriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-coach': {
      id: '/career-coach'
      path: '/career-coach'
      fullPath: '/career-coach'
      preLoaderRoute: typeof CareerCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-consultant': {
      id: '/business-consultant'
      path: '/business-consultant'
      fullPath: '/business-consultant'
      preLoaderRoute: typeof BusinessConsultantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-agents': {
      id: '/all-agents'
      path: '/all-agents'
      fullPath: '/all-agents'
      preLoaderRoute: typeof AllAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-writer': {
      id: '/academic-writer'
      path: '/academic-writer'
      fullPath: '/academic-writer'
      preLoaderRoute: typeof AcademicWriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise/login': {
      id: '/enterprise/login'
      path: '/enterprise/login'
      fullPath: '/enterprise/login'
      preLoaderRoute: typeof EnterpriseLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise/dashboard': {
      id: '/enterprise/dashboard'
      path: '/enterprise/dashboard'
      fullPath: '/enterprise/dashboard'
      preLoaderRoute: typeof EnterpriseDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicWriterRoute: AcademicWriterRoute,
  AllAgentsRoute: AllAgentsRoute,
  AuthRoute: AuthRoute,
  BusinessConsultantRoute: BusinessConsultantRoute,
  CareerCoachRoute: CareerCoachRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  ContentWriterRoute: ContentWriterRoute,
  DashboardRoute: DashboardRoute,
  EventPlannerRoute: EventPlannerRoute,
  ExamPrepRoute: ExamPrepRoute,
  ExamSuccessRoute: ExamSuccessRoute,
  FinanceAdvisorRoute: FinanceAdvisorRoute,
  HomeManagementRoute: HomeManagementRoute,
  LanguageCoachRoute: LanguageCoachRoute,
  PersonalShopperRoute: PersonalShopperRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  TranslationHubRoute: TranslationHubRoute,
  TravelPlannerRoute: TravelPlannerRoute,
  VideoProductionRoute: VideoProductionRoute,
  WellnessCoachRoute: WellnessCoachRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  EnterpriseDashboardRoute: EnterpriseDashboardRoute,
  EnterpriseLoginRoute: EnterpriseLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
